USE [DataHIS] 
GO

IF OBJECT_ID('[dbo].[ESTABLECIMIENTOS]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE ESTABLECIMIENTOS
	PRINT 'TABLA LIMPIADA ESTABLECIMIENTOS'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_CP]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_CP
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_CP'
END  
GO
IF OBJECT_ID('[dbo].[CIE_CPMS]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE CIE_CPMS
	PRINT 'TABLA LIMPIADA CIE_CPMS'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_COLEGIO]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_COLEGIO
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_COLEGIO'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_CONTRATO]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_CONTRATO
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_CONTRATO'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_ETNIA]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_ETNIA
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_ETNIA'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_FINANCIADOR]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_FINANCIADOR
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_FINANCIADOR'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_PAIS]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_PAIS
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_PAIS'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_PROFESION]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_PROFESION
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_PROFESION'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_TIPO_DOC]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_TIPO_DOC
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_TIPO_DOC'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_UBIGEO_INEI_RENIEC]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_UBIGEO_INEI_RENIEC
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_UBIGEO_INEI_RENIEC'
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_HIS_UPS]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE MAESTRO_HIS_UPS
	PRINT 'TABLA LIMPIADA MAESTRO_HIS_UPS'
END
GO
IF OBJECT_ID('[dbo].[PERIODO]', 'U') IS NOT NULL
BEGIN
	TRUNCATE TABLE PERIODO
	PRINT 'TABLA LIMPIADA PERIODO'
END
GO
DECLARE @NombreRuta VARCHAR(250), 
		@NombreRutaArchivoEESS VARCHAR(250), 
		@NombreRutaArchivoCentroPoblado VARCHAR(250), 
		@NombreRutaArchivoCIE_CPMS VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_COLEGIO VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_CONTRATO VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_ETNIA VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_FINANCIADOR VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_PAIS VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_PROFESION VARCHAR(250), 
		@NombreRutaArchivoMAESTRO_HIS_TIPO_DOC VARCHAR(250),
		@NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC VARCHAR(250),
		@NombreRutaArchivoMAESTRO_HIS_UPS VARCHAR(250), 

		@StrExe NVARCHAR(MAX),
		@Existe INT,
		@Codepage INT

--- Agregar la condicion codepage permite que las letras ñ o tildes se puedan ver de manera correcta
--- Por default esta en 0(CERO), si deseas ver de manera correcta @Codepage 1(UNO)
SET @Codepage=1
--==============================================================================================

PRINT '<===================INICIO DE IMPORTACION===================>'

SET @NombreRuta = 'C:\HISMINSA\MAESTROS\MaestrosHisCsv'
SET	@NombreRutaArchivoEESS = @NombreRuta +'\MAESTRO_HIS_ESTABLECIMIENTO.csv'
SET	@NombreRutaArchivoCentroPoblado = @NombreRuta +'\MAESTRO_HIS_CENTRO_POBLADO.csv'
SET	@NombreRutaArchivoCIE_CPMS = @NombreRuta +'\MAESTRO_HIS_CIE_CPMS.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_COLEGIO = @NombreRuta +'\MAESTRO_HIS_COLEGIO.csv' 
SET	@NombreRutaArchivoMAESTRO_HIS_CONTRATO = @NombreRuta +'\MAESTRO_HIS_CONDICION_CONTRATO.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_ETNIA = @NombreRuta +'\MAESTRO_HIS_ETNIA.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_FINANCIADOR = @NombreRuta +'\MAESTRO_HIS_FINANCIADOR.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_PAIS = @NombreRuta +'\MAESTRO_HIS_PAIS.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_PROFESION = @NombreRuta +'\MAESTRO_HIS_PROFESION.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_TIPO_DOC = @NombreRuta +'\MAESTRO_HIS_TIPO_DOC.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC = @NombreRuta +'\MAESTRO_HIS_UBIGEO_INEI_RENIEC.csv'
SET	@NombreRutaArchivoMAESTRO_HIS_UPS = @NombreRuta +'\MAESTRO_HIS_UPS.csv'

-- INSERT ESTABLECIMIENTOS
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoEESS , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT ESTABLECIMIENTOS ' +
					' FROM ''' + @NombreRutaArchivoEESS + ''''
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoEESS)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoEESS);
END

-- INSERT CENTRO POBLADO
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoCentroPoblado , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_CP ' +
					' FROM ''' + @NombreRutaArchivoCentroPoblado + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoCentroPoblado)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoCentroPoblado);
END

-- INSERT CIE_CPMS
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoCIE_CPMS , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT CIE_CPMS ' +
					' FROM ''' + @NombreRutaArchivoCIE_CPMS + ''''
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoCIE_CPMS)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoCIE_CPMS);
END

-- INSERT MAESTRO_HIS_COLEGIO
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_COLEGIO , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_COLEGIO ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_COLEGIO + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_COLEGIO)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_COLEGIO);
END

-- INSERT MAESTRO_HIS_CONTRATO
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_CONTRATO , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_CONTRATO ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_CONTRATO + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_CONTRATO)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_CONTRATO);
END
		
-- INSERT MAESTRO_HIS_ETNIA
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_ETNIA , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_ETNIA ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_ETNIA + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_ETNIA)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_ETNIA);
END

-- INSERT MAESTRO_HIS_FINANCIADOR
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_FINANCIADOR , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_FINANCIADOR ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_FINANCIADOR + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_FINANCIADOR)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_FINANCIADOR);
END

-- INSERT MAESTRO_HIS_PAIS
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_PAIS , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_PAIS ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_PAIS + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_PAIS)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_PAIS);
END

-- INSERT MAESTRO_HIS_PROFESION
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_PROFESION , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_PROFESION ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_PROFESION + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_PROFESION)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_PROFESION);
END

-- INSERT MAESTRO_HIS_TIPO_DOC
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_TIPO_DOC , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_TIPO_DOC ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_TIPO_DOC + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_TIPO_DOC)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_TIPO_DOC);
END
		
-- INSERT MAESTRO_HIS_UBIGEO_INEI_RENIEC
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_UBIGEO_INEI_RENIEC ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_UBIGEO_INEI_RENIEC);
END

-- INSERT MAESTRO_HIS_UPS
SET @Existe = 0
EXEC Master.dbo.xp_fileexist @NombreRutaArchivoMAESTRO_HIS_UPS , @Existe OUT
IF @Existe = 1
BEGIN
	SET @StrExe = 	' BULK INSERT MAESTRO_HIS_UPS ' +
					' FROM ''' + @NombreRutaArchivoMAESTRO_HIS_UPS + ''''
	
	IF(@Codepage=1)
	BEGIN
		SET @StrExe = @StrExe + ' WITH (CODEPAGE = ''65001'', FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
	ELSE
	BEGIN
		SET @StrExe = @StrExe + ' WITH (FIRSTROW =2, FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', TABLOCK)'
	END
		
	EXEC SP_EXECUTESQL @StrExe
	PRINT('EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_UPS)
END
ELSE
BEGIN
	PRINT('NO EXISTE EL ARCHIVO '+ @NombreRutaArchivoMAESTRO_HIS_UPS);
END
GO
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 1, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 2, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 3, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 4, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 5, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 6, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 7, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 8, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 9, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 10, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 11, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2018, 12, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 1, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 2, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 3, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 4, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 5, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 6, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 7, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 8, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 9, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 10, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 11, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2019, 12, 0)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 1, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 2, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 3, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 4, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 5, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 6, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 7, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 8, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 9, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 10, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 11, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2020, 12, 1)

INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 1, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 2, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 3, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 4, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 5, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 6, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 7, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 8, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 9, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 10, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 11, 1)
INSERT [dbo].[PERIODO] ([I_ANIO], [I_MES], [I_ESTADO]) VALUES (2021, 12, 1)
GO




PRINT '<===================FIN DE IMPORTACION===================>'