
use DataHIS
GO
alter VIEW [dbo].[V_ATENDIDOS]AS
SELECT        Descripcion_Red AS RED, Descripcion_MicroRed AS MicroRed, RENAES, ESTABLECIMIENTO, Nro_Doc_Personal AS DOC_ATIENDE,PERSONAL, 
						Descripcion_Colegio AS COLEGIO, Descripcion_Profesion AS PROFESION, Descripcion_Ups AS SERVICIO, 
                         FECHA, Anio, Mes, 
                         SUM(CASE WHEN (DIA = 1 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [01_EESS], 
                         SUM(CASE WHEN (DIA = 2 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [02_EESS], 
                         SUM(CASE WHEN (DIA = 3 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [03_EESS], 
                         SUM(CASE WHEN (DIA = 4 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [04_EESS], 
                         SUM(CASE WHEN (DIA = 5 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [05_EESS], 
                         SUM(CASE WHEN (DIA = 6 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [06_EESS], 
                         SUM(CASE WHEN (DIA = 7 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [07_EESS], 
                         SUM(CASE WHEN (DIA = 8 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [08_EESS], 
                         SUM(CASE WHEN (DIA = 9 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [09_EESS], 
                         SUM(CASE WHEN (DIA = 10 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [10_EESS], 
                         SUM(CASE WHEN (DIA = 11 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [11_EESS], 
                         SUM(CASE WHEN (DIA = 12 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [12_EESS], 
                         SUM(CASE WHEN (DIA = 13 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [13_EESS], 
                         SUM(CASE WHEN (DIA = 14 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [14_EESS], 
                         SUM(CASE WHEN (DIA = 15 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [15_EESS], 
                         SUM(CASE WHEN (DIA = 16 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [16_EESS], 
                         SUM(CASE WHEN (DIA = 17 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [17_EESS], 
                         SUM(CASE WHEN (DIA = 18 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [18_EESS], 
                         SUM(CASE WHEN (DIA = 19 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [19_EESS], 
                         SUM(CASE WHEN (DIA = 20 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [20_EESS], 
                         SUM(CASE WHEN (DIA = 21 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [21_EESS], 
                         SUM(CASE WHEN (DIA = 22 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [22_EESS], 
                         SUM(CASE WHEN (DIA = 23 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [23_EESS], 
                         SUM(CASE WHEN (DIA = 24 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [24_EESS], 
                         SUM(CASE WHEN (DIA = 25 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [25_EESS], 
                         SUM(CASE WHEN (DIA = 26 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [26_EESS], 
                         SUM(CASE WHEN (DIA = 27 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [27_EESS], 
                         SUM(CASE WHEN (DIA = 28 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [28_EESS], 
                         SUM(CASE WHEN (DIA = 29 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [29_EESS], 
                         SUM(CASE WHEN (DIA = 30 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [30_EESS], 
                         SUM(CASE WHEN (DIA = 31 AND COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [31_EESS], 
                         SUM(CASE WHEN (COND_EESS IN ('N', 'R')) THEN 1 ELSE 0 END) AS [Total Atendidos EESS],
                         
                         SUM(CASE WHEN (DIA = 1 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [01_Serv], 
                         SUM(CASE WHEN (DIA = 2 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [02_Serv], 
                         SUM(CASE WHEN (DIA = 3 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [03_Serv], 
                         SUM(CASE WHEN (DIA = 4 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [04_Serv], 
                         SUM(CASE WHEN (DIA = 5 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [05_Serv], 
                         SUM(CASE WHEN (DIA = 6 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [06_Serv], 
                         SUM(CASE WHEN (DIA = 7 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [07_Serv], 
                         SUM(CASE WHEN (DIA = 8 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [08_Serv], 
                         SUM(CASE WHEN (DIA = 9 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [09_Serv], 
                         SUM(CASE WHEN (DIA = 10 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [10_Serv], 
                         SUM(CASE WHEN (DIA = 11 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [11_Serv], 
                         SUM(CASE WHEN (DIA = 12 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [12_Serv], 
                         SUM(CASE WHEN (DIA = 13 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [13_Serv], 
                         SUM(CASE WHEN (DIA = 14 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [14_Serv], 
                         SUM(CASE WHEN (DIA = 15 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [15_Serv], 
                         SUM(CASE WHEN (DIA = 16 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [16_Serv], 
                         SUM(CASE WHEN (DIA = 17 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [17_Serv], 
                         SUM(CASE WHEN (DIA = 18 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [18_Serv], 
                         SUM(CASE WHEN (DIA = 19 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [19_Serv], 
                         SUM(CASE WHEN (DIA = 20 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [20_Serv], 
                         SUM(CASE WHEN (DIA = 21 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [21_Serv], 
                         SUM(CASE WHEN (DIA = 22 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [22_Serv], 
                         SUM(CASE WHEN (DIA = 23 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [23_Serv], 
                         SUM(CASE WHEN (DIA = 24 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [24_Serv], 
                         SUM(CASE WHEN (DIA = 25 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [25_Serv], 
                         SUM(CASE WHEN (DIA = 26 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [26_Serv], 
                         SUM(CASE WHEN (DIA = 27 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [27_Serv], 
                         SUM(CASE WHEN (DIA = 28 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [28_Serv], 
                         SUM(CASE WHEN (DIA = 29 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [29_Serv], 
                         SUM(CASE WHEN (DIA = 30 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [30_Serv], 
                         SUM(CASE WHEN (DIA = 31 AND COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [31_Serv], 
                         SUM(CASE WHEN (COND_SERV IN ('N', 'R')) THEN 1 ELSE 0 END) AS [Total Atendidos Servicios]
FROM  dbo.V_HISMINSA
WHERE        (Id_Paciente IS NULL) AND (Id_C = 1 AND ID_L=1)
GROUP BY Descripcion_Red, Descripcion_MicroRed, RENAES, Establecimiento, Nro_Doc_Personal, Personal, Descripcion_Colegio, 
         Descripcion_Profesion, Descripcion_Ups, Fecha, Anio, Mes
HAVING (SUM(CASE WHEN (Cond_Serv IN ('N', 'R')) THEN 1 ELSE 0 END) > 0)

GO
PRINT 'VISTA CREADA V_ATENDIDOS'
GO
alter VIEW [dbo].[V_ATENCIONES]AS
SELECT        Descripcion_Red AS RED, Descripcion_MicroRed AS MicroRed, RENAES, ESTABLECIMIENTO, Nro_Doc_Personal AS DOC_ATIENDE, 
                         PERSONAL, Descripcion_Colegio AS COLEGIO, Descripcion_Profesion AS PROFESION, Descripcion_Ups AS SERVICIO, 
                         Fecha AS FECHA, Anio, Mes, 
                         SUM(CASE WHEN (DIA = 1 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [01_EESS], 
                         SUM(CASE WHEN (DIA = 2 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [02_EESS], 
                         SUM(CASE WHEN (DIA = 3 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [03_EESS], 
                         SUM(CASE WHEN (DIA = 4 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [04_EESS], 
                         SUM(CASE WHEN (DIA = 5 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [05_EESS], 
                         SUM(CASE WHEN (DIA = 6 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [06_EESS], 
                         SUM(CASE WHEN (DIA = 7 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [07_EESS], 
                         SUM(CASE WHEN (DIA = 8 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [08_EESS], 
                         SUM(CASE WHEN (DIA = 9 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [09_EESS], 
                         SUM(CASE WHEN (DIA = 10 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [10_EESS], 
                         SUM(CASE WHEN (DIA = 11 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [11_EESS], 
                         SUM(CASE WHEN (DIA = 12 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [12_EESS], 
                         SUM(CASE WHEN (DIA = 13 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [13_EESS], 
                         SUM(CASE WHEN (DIA = 14 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [14_EESS], 
                         SUM(CASE WHEN (DIA = 15 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [15_EESS], 
                         SUM(CASE WHEN (DIA = 16 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [16_EESS], 
                         SUM(CASE WHEN (DIA = 17 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [17_EESS], 
                         SUM(CASE WHEN (DIA = 18 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [18_EESS], 
                         SUM(CASE WHEN (DIA = 19 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [19_EESS], 
                         SUM(CASE WHEN (DIA = 20 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [20_EESS], 
                         SUM(CASE WHEN (DIA = 21 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [21_EESS], 
                         SUM(CASE WHEN (DIA = 22 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [22_EESS], 
                         SUM(CASE WHEN (DIA = 23 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [23_EESS], 
                         SUM(CASE WHEN (DIA = 24 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [24_EESS], 
                         SUM(CASE WHEN (DIA = 25 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [25_EESS], 
                         SUM(CASE WHEN (DIA = 26 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [26_EESS], 
                         SUM(CASE WHEN (DIA = 27 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [27_EESS], 
                         SUM(CASE WHEN (DIA = 28 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [28_EESS], 
                         SUM(CASE WHEN (DIA = 29 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [29_EESS], 
                         SUM(CASE WHEN (DIA = 30 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [30_EESS], 
                         SUM(CASE WHEN (DIA = 31 AND COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [31_EESS], 
                         SUM(CASE WHEN (COND_EESS IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [Total Atenciones EESS],
                         
                         SUM(CASE WHEN (DIA = 1 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [01_Serv], 
                         SUM(CASE WHEN (DIA = 2 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [02_Serv], 
                         SUM(CASE WHEN (DIA = 3 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [03_Serv], 
                         SUM(CASE WHEN (DIA = 4 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [04_Serv], 
                         SUM(CASE WHEN (DIA = 5 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [05_Serv], 
                         SUM(CASE WHEN (DIA = 6 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [06_Serv], 
                         SUM(CASE WHEN (DIA = 7 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [07_Serv], 
                         SUM(CASE WHEN (DIA = 8 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [08_Serv], 
                         SUM(CASE WHEN (DIA = 9 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [09_Serv], 
                         SUM(CASE WHEN (DIA = 10 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [10_Serv], 
                         SUM(CASE WHEN (DIA = 11 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [11_Serv], 
                         SUM(CASE WHEN (DIA = 12 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [12_Serv], 
                         SUM(CASE WHEN (DIA = 13 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [13_Serv], 
                         SUM(CASE WHEN (DIA = 14 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [14_Serv], 
                         SUM(CASE WHEN (DIA = 15 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [15_Serv], 
                         SUM(CASE WHEN (DIA = 16 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [16_Serv], 
                         SUM(CASE WHEN (DIA = 17 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [17_Serv], 
                         SUM(CASE WHEN (DIA = 18 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [18_Serv], 
                         SUM(CASE WHEN (DIA = 19 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [19_Serv], 
                         SUM(CASE WHEN (DIA = 20 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [20_Serv], 
                         SUM(CASE WHEN (DIA = 21 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [21_Serv], 
                         SUM(CASE WHEN (DIA = 22 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [22_Serv], 
                         SUM(CASE WHEN (DIA = 23 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [23_Serv], 
                         SUM(CASE WHEN (DIA = 24 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [24_Serv], 
                         SUM(CASE WHEN (DIA = 25 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [25_Serv], 
                         SUM(CASE WHEN (DIA = 26 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [26_Serv], 
                         SUM(CASE WHEN (DIA = 27 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [27_Serv], 
                         SUM(CASE WHEN (DIA = 28 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [28_Serv], 
                         SUM(CASE WHEN (DIA = 29 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [29_Serv], 
                         SUM(CASE WHEN (DIA = 30 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [30_Serv], 
                         SUM(CASE WHEN (DIA = 31 AND Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [31_Serv], 
                         SUM(CASE WHEN (Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) AS [Total Atenciones Servicios]
                         
FROM            dbo.V_HISMINSA h
WHERE        (Id_Paciente IS NULL) AND (Id_C = 1 AND ID_L=1)
GROUP BY Descripcion_Red, Descripcion_MicroRed, RENAES, Establecimiento, Nro_Doc_Personal, Personal, Descripcion_Colegio, 
                         Descripcion_Profesion, Descripcion_Ups, Fecha, Anio, Mes
HAVING        (SUM(CASE WHEN (Cond_Serv IN ('N', 'R', 'C')) THEN 1 ELSE 0 END) > 0)
GO
PRINT 'VISTA CREADA V_ATENCIONES'
GO