IF NOT EXISTS (SELECT dbid FROM sysdatabases WHERE name = 'BDHIS_MINSA') 
BEGIN
	PRINT 'NO EXISTE LA BASE DE DATOS BDHIS_MINSA'
    CREATE DATABASE BDHIS_MINSA
	PRINT 'CREANDO LA BASE DE DATOS BDHIS_MINSA'
END
ELSE
BEGIN
    PRINT 'YA EXISTE LA BASE DE DATOS BDHIS_MINSA'
END

GO

USE [BDHIS_MINSA]
IF OBJECT_ID('[dbo].[TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT]', 'U') IS NULL
BEGIN
	PRINT N'Creating [dbo].[TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT]...';
	CREATE TABLE [dbo].[TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT](
	[I_ID] [int] IDENTITY(1,1) NOT NULL,
	[V_ID_IDENTIFICADOR_ACTUALIZACION] varchar(100) NOT NULL,
	[V_DESCRIPCION_ACTUALIZACION] varchar(250) NOT NULL,	
	[D_FECHA_EJECUCION] datetime NOT NULL);
 END
 ELSE PRINT N'Ya ha sido creada [dbo].[TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT]...'

DECLARE 
@V_IDENTIFICADOR VARCHAR(100)

SET @V_IDENTIFICADOR='IMPORTACION_ARCHIVOS_PLANOS_VERSION_13_0_0'

IF EXISTS (SELECT V_ID_IDENTIFICADOR_ACTUALIZACION  FROM TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT WHERE V_ID_IDENTIFICADOR_ACTUALIZACION=@V_IDENTIFICADOR)
BEGIN
	PRINT N'EL SCRIPT ' + @V_IDENTIFICADOR + ' ya ha sido ejecutado'
END
ELSE
BEGIN
	--INICIO
	--FIN
	INSERT INTO TBL_HISTORIAL_ACTUALIZACIONES_SCRIPT ([V_ID_IDENTIFICADOR_ACTUALIZACION], [V_DESCRIPCION_ACTUALIZACION], [D_FECHA_EJECUCION])
	VALUES (@V_IDENTIFICADOR, 'IMPORTACION ARCHIVOS PLANOS VERSION 13.0.0', GETDATE())

	PRINT N'EL SCRIPT ' + @V_IDENTIFICADOR + ' se ejecuto satisfactoriamente'
END