USE [BDHIS_MINSA]
-- ====================================================================
-- Creador			:	Martin Juan Gerardo Jaramillo Morales
-- Apoyo			:	
-- Fecha Creación	:	20200618
-- Descripcion		:	Elimina todas las tablas para que no existan errores al momento de crearlas.
-- ====================================================================
GO
PRINT '=================>>>>>>>>> INICIO DE PROCESO HISMINSA_LOCAL_001_SCRIPT_LIMPIAR_TABLAS <<<<<<<<<================='
GO
PRINT '=================>>>>>>>>> INICIO DE PROCESO HISMINSA_LOCAL_002_SCRIPT_VALIDACION_TABLAS <<<<<<<<<================='
GO
IF OBJECT_ID('[dbo].[TBM_ANIOS_MES_ARCHIVO_PLANO]', 'U') IS NOT NULL
BEGIN
	DROP TABLE TBM_ANIOS_MES_ARCHIVO_PLANO
	PRINT 'SE ELIMINO LA TABLA TBM_ANIOS_MES_ARCHIVO_PLANO'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
PRINT '=================>>>>>>>>> INICIO LIMPIEZA DE HISMINSA_LOCAL_003_SCRIPT_IMPORTAR_ARCHIVOS_PLANOS <<<<<<<<<================='
GO
IF OBJECT_ID('[dbo].[TBM_ANIOS_MES_ARCHIVO_PLANO_TMP]', 'U') IS NOT NULL
BEGIN
	DROP TABLE TBM_ANIOS_MES_ARCHIVO_PLANO_TMP
	PRINT 'SE ELIMINO LA TABLA TBM_ANIOS_MES_ARCHIVO_PLANO_TMP'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='	
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_REGISTRADOR]', 'U') IS NOT NULL
BEGIN
	DROP TABLE MAESTRO_REGISTRADOR
	PRINT 'SE ELIMINO LA TABLA MAESTRO_REGISTRADOR'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='	
END
GO
IF OBJECT_ID('[dbo].[MAESTRO_PERSONAL]', 'U') IS NOT NULL
BEGIN
	DROP TABLE MAESTRO_PERSONAL
	PRINT 'SE ELIMINO LA TABLA MAESTRO_PERSONAL'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='	
END  
GO
IF OBJECT_ID('[dbo].[MAESTRO_PACIENTE]', 'U') IS NOT NULL
BEGIN
	DROP TABLE MAESTRO_PACIENTE
	PRINT 'SE ELIMINO LA TABLA MAESTRO_PACIENTE'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='		
END
GO
IF OBJECT_ID('[dbo].[NOMINAL_TRAMA_NUEVO]', 'U') IS NOT NULL
BEGIN
	DROP TABLE NOMINAL_TRAMA_NUEVO
	PRINT 'SE ELIMINO LA TABLA NOMINAL_TRAMA_NUEVO'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='			
END
GO
PRINT '=================>>>>>>>>> INICIO LIMPIEZA DE HISMINSA_LOCAL_004_SCRIPT_VISTAS_TABLAS_MAESTRAS_ARCHIVOS_PLANOS_DETALLADO <<<<<<<<<================='
GO
IF OBJECT_ID('[dbo].[V_CONSOLIDADO_NUEVA_TRAMA_HISMINSA]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_CONSOLIDADO_NUEVA_TRAMA_HISMINSA
	PRINT 'SE ELIMINO V_CONSOLIDADO_NUEVA_TRAMA_HISMINSA'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
IF OBJECT_ID('[dbo].[T_CONSOLIDADO_NUEVA_TRAMA_HISMINSA]', 'U') IS NOT NULL
BEGIN
	DROP TABLE T_CONSOLIDADO_NUEVA_TRAMA_HISMINSA
	PRINT 'SE ELIMINO T_CONSOLIDADO_NUEVA_TRAMA_HISMINSA'
    PRINT '=================>>>>>>>>>'	
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_ATENCIONES_ATENDIDOS_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_ATENCIONES_ATENDIDOS_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_ATENCIONES_ATENDIDOS_DETALLADO'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_PRODUCCION_ATENCION_DIARIO_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_PRODUCCION_ATENCION_DIARIO_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_PRODUCCION_ATENCION_DIARIO_DETALLADO'
    PRINT '=================>>>>>>>>> <<<<<<<<<================='	
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_PRODUCCION_ATENCION_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_PRODUCCION_ATENCION_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_PRODUCCION_ATENCION_DETALLADO'
	PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_PRODUCCION_DIGITADOR_DIARIO_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_PRODUCCION_DIGITADOR_DIARIO_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_PRODUCCION_DIGITADOR_DIARIO_DETALLADO'
	PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_PRODUCCION_DIGITADOR_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_PRODUCCION_DIGITADOR_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_PRODUCCION_DIGITADOR_DETALLADO'
	PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
IF OBJECT_ID('[dbo].[V_REPORTE_REPORTE40A_DETALLADO]', 'V') IS NOT NULL
BEGIN
	DROP VIEW V_REPORTE_REPORTE40A_DETALLADO
	PRINT 'SE ELIMINO V_REPORTE_REPORTE40A_DETALLADO'
	PRINT '=================>>>>>>>>> <<<<<<<<<================='
END
GO
PRINT '=================>>>>>>>>> FIN DE PROCESO HISMINSA_LOCAL_001_SCRIPT_LIMPIAR_TABLAS <<<<<<<<<================='