/******************************************************************
	SCRIPT CREADO POR MG.SC.ING. SISTEMAS HAROLD N. COILA VILLENA
	JEFE DE LA UNIDAD DE ESTADISTICA E INFORMATICA 2022
*******************************************************************/
USE [BDHIS_MINSA]; SET LANGUAGE SPANISH; DECLARE @hAnioAct VARCHAR(4); SET @hAnioAct=YEAR(GETDATE());
DECLARE @hFechaInicio VARCHAR(8),@hFechaFin VARCHAR(8),@hFechaHoy VARCHAR(8)=REPLACE(CAST(GETDATE() AS Date),'-','');
DECLARE @hDistrito VARCHAR(255)='%',@hMicrored VARCHAR(200)='%',@hEstablecimiento VARCHAR(200)='%',@hUPS VARCHAR(255)='%';
/******************************************************************
	DESIGNE LOS FILTROS QUE DESEA OBVIAR A CONTINUACION
	AGREGANDO '-- ', sin comillas ANTES DE ETIQUETA 'SET'
*******************************************************************/
SET @hFechaInicio = '20220101';
SET @hFechaFin = '20220131';
-- SET @hFechaFin = @hFechaHoy;

/*******************************************************************
	FIN DEL SETEO DE LOS FILTROS, NO ALTERAR EL CODIGO
	MAESTRO SIGUIENTE CREADO EN 07 DE ENERO DEL 2022
********************************************************************/
SELECT
	N.ANIO AS [AÑO],
	UPPER(DATENAME(MONTH,'01/'+MES+'/'+@hAnioAct)) AS [MES],
	IIF(ME.MICRORED = 'NO PERTENECE A NINGUNA MICRORED','REDESS HNE',ME.MICRORED) AS [MICRORED],
	IIF(ME.NOMBRE_ESTABLECIMIENTO = 'HOSPITAL LUCIO ALDAZABAL PAUCA','HOSPITAL LAP',ME.NOMBRE_ESTABLECIMIENTO) AS [ESTABLECIMIENTO],
	COUNT(DISTINCT ID_PACIENTE) AS [TOTAL PACIENTES COVID]
FROM
	NOMINAL_TRAMA_NUEVO AS N
	INNER JOIN MAESTRO_HIS_ESTABLECIMIENTO AS ME ON	N.ID_ESTABLECIMIENTO = ME.ID_ESTABLECIMIENTO
WHERE
	N.FECHA_ATENCION>=@hFechaInicio AND N.FECHA_ATENCION<=@hFechaFin
	AND
	N.ID_CITA IN (
		SELECT DISTINCT ID_CITA FROM NOMINAL_TRAMA_NUEVO
		WHERE CODIGO_ITEM IN ('U071','U072','B972','Z208')
	)
GROUP BY
	N.ANIO, 
	N.MES,
	ME.MICRORED,
	ME.NOMBRE_ESTABLECIMIENTO
ORDER BY
	N.ANIO,
	CAST(N.MES AS INT),
	ME.MICRORED,
	ME.NOMBRE_ESTABLECIMIENTO
	ASC;