/******************************************************************
	SCRIPT CREADO POR MG.SC.ING. SISTEMAS HAROLD N. COILA VILLENA
	JEFE DE LA UNIDAD DE ESTADISTICA E INFORMATICA 2022
*******************************************************************/
USE [BDHIS_MINSA]; SET LANGUAGE SPANISH; DECLARE @hAnioAct VARCHAR(4); SET @hAnioAct=YEAR(GETDATE());
DECLARE @hFechaInicio VARCHAR(8),@hFechaFin VARCHAR(8),@hFechaHoy VARCHAR(8)=REPLACE(CAST(GETDATE() AS Date),'-','');
DECLARE @hDistrito VARCHAR(255)='%',@hMicrored VARCHAR(200)='%',@hEstablecimiento VARCHAR(200)='%',@hUPS VARCHAR(255)='%',@hDNIPRO VARCHAR(8)='%';
/******************************************************************
	DESIGNE LOS FILTROS QUE DESEA OBVIAR A CONTINUACION
	AGREGANDO '-- ', sin comillas ANTES DE ETIQUETA 'SET'
*******************************************************************/
-- SET @hUPS='ATENCION PSICOLOGICA Y SALUD MENTAL EN EMERGENCIAS Y DESASTRES'
SET @hFechaInicio = '20220101';
SET @hFechaFin = '20220131';
-- SET @hFechaFin = @hFechaHoy; 
-- SET @hMicrored = 'PUTINA';
SET @hEstablecimiento = 'huarisani';
-- SET @hDNIPRO = '01284739';

/*******************************************************************
	FIN DEL SETEO DE LOS FILTROS, NO ALTERAR EL CODIGO
	MAESTRO SIGUIENTE CREADO EN 07 DE ENERO DEL 2022
********************************************************************/
SELECT 
	IIF(ME.MICRORED = 'NO PERTENECE A NINGUNA MICRORED','REDESS HNE',ME.MICRORED) AS [MICRORED],
	IIF(ME.NOMBRE_ESTABLECIMIENTO = 'HOSPITAL LUCIO ALDAZABAL PAUCA','HOSPITAL LAP',ME.NOMBRE_ESTABLECIMIENTO) AS [ESTABLECIMIENTO],
	ISNULL(MP.NUMERO_DOCUMENTO_PERSONAL,'') AS [DNI PROFESIONAL],
	ISNULL(CONCAT(MP.APELLIDO_PATERNO_PERSONAL,' ',MP.APELLIDO_MATERNO_PERSONAL,' ',MP.NOMBRES_PERSONAL),'') AS [NOMBRE PROFESIONAL],
	ISNULL(MU.DESCRIPCION_UPS,'') AS [SERVICIO UPS],
	RP.ANIO AS [AÑO],
	UPPER(DATENAME(MONTH,'01/'+MES+'/'+@hAnioAct)) AS [MES],
	RP.DIA AS [DIA],

	/********** LIBERAR PARA MAS DETALLES *************
	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Servicio IN ('N') ) THEN 1 ELSE 0 END) AS [NUEVO],
	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Servicio IN ('C') ) THEN 1 ELSE 0 END) AS [CONTI],
	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Servicio IN ('R') ) THEN 1 ELSE 0 END) AS [REINGR],

	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Establecimiento IN ('N', 'R') ) THEN 1 ELSE 0 END) AS [ATE. EESS],				
	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Servicio IN ('N', 'R') ) THEN 1 ELSE 0 END) AS [ATE. SERVICIO],
	SUM(CASE WHEN (rp.Id_Paciente LIKE 'APP%' ) THEN 1 ELSE 0 END) AS [APP],
	SUM(CASE WHEN (rp.Id_Paciente LIKE 'AAA%' ) THEN 1 ELSE 0 END) AS [AAA],
	***************************************************/

	SUM(CASE WHEN (rp.Id_Paciente IS NOT NULL AND rp.Id_Condicion_Servicio IN ('N', 'R', 'C') ) THEN 1 ELSE 0 END) AS [TOTAL ATENCIONES]
FROM
	T_CONSOLIDADO_NUEVA_TRAMA_HISMINSA RP
	INNER JOIN DBO.MAESTRO_PERSONAL MP ON MP.ID_PERSONAL = RP.ID_PERSONAL
	INNER JOIN DBO.MAESTRO_HIS_ESTABLECIMIENTO ME ON ME.ID_ESTABLECIMIENTO = RP.ID_ESTABLECIMIENTO
	INNER JOIN DBO.MAESTRO_HIS_UPS MU ON MU.ID_UPS = RP.ID_UPS
WHERE    
	RP.FECHA_ATENCION>=@hFechaInicio AND RP.FECHA_ATENCION<=@hFechaFin
	AND
	ME.MICRORED LIKE @hMicrored AND ME.Nombre_Establecimiento LIKE @hEstablecimiento
	AND
	MP.NUMERO_DOCUMENTO_PERSONAL LIKE @hDNIPRO
	AND
	MU.DESCRIPCION_UPS LIKE @hUPS
GROUP BY
	ME.MICRORED,
	ME.NOMBRE_ESTABLECIMIENTO,
	MP.NUMERO_DOCUMENTO_PERSONAL,
	MP.APELLIDO_PATERNO_PERSONAL,
	MP.APELLIDO_MATERNO_PERSONAL,
	MP.NOMBRES_PERSONAL,
	RP.ID_ESTABLECIMIENTO,
	MU.DESCRIPCION_UPS,
	RP.ID_PERSONAL,
	RP.ANIO,
	RP.MES,
	RP.DIA
ORDER BY
	ME.MICRORED,
	ME.NOMBRE_ESTABLECIMIENTO,
	CONCAT(MP.APELLIDO_PATERNO_PERSONAL,' ',MP.APELLIDO_MATERNO_PERSONAL,' ',MP.NOMBRES_PERSONAL)
	ASC;