/*==============================================================================
ELABORACION: OGTI/ OGEI - MINSA 
INDICADORES: DL1153 - 2021
-----------------------------------------------------------------------

Indicadores DL-1153
---------------------	

Nombre: Porcentaje de ni�as/ni�os menores de 18 meses, sin diagn�stico de anemia entre los 6 y 11 meses
, que reciben un paquete integrado de servicios preventivos: CRED, vacunas, dosaje de hemoglobina para descarte de anemia y suplementaci�n con hierro.

Sintaxis:
Numerador: Total de ni�as/ni�os del denominador que recibieron paquete integrado de servicios preventivos (registrado en el HIS)
, de acuerdo al esquema vigente: CRED, vacunas, dosaje de hemoglobina para descarte de anemia y suplementaci�n con hierro.

Sintaxis: Suma de DNIs que forman parte del denominador y cuentan con: (Se agregan los Z)
1. Hasta los 454 d�as (14 meses y 29 d�as) 
3 dosis de vacuna Antipolio (CPMS: 90712 � 90713)
3 dosis de vacuna Pentavalente (CPMS: 90723)
1 dosis de vacuna contra Influenza (CPMS: 90657)
2 dosis de vacuna contra Rotavirus (m�ximo hasta 7 meses 29 d�as) (CPMS: 90681)
3 dosis de vacuna contra Neumococo (CPMS: 90670)
1 dosis de vacuna SPR (CPMS: 90707)
Y
2. Entre los 29 y 364 d�as (11 meses 29 d�as), al menos a recibido:
1� Control:    29 d�as    hasta      59 dias
2� Control:    02 meses   hasta      119 dias
3� Control:    04 meses   hasta	     179 dias
4� Control:    06 meses   hasta      269 dias
5� Control:    09 meses   hasta      364 dias
Y
3. Con dosaje definitivo de hemoglobina (CPMS: 85018 � CIE: Z017) entre los 170 y 269 d�as (6 y 8 meses 29 d�as).
Y
4. A partir de la fecha del primer dosaje definitivo de hemoglobina entre los 170 y 269 d�as de edad, 
inician oportunamente la suplementaci�n preventiva con hierro (hasta 7 d�as despu�s de la fecha de dosaje) 
y continuan durante 06 meses con un rango de 25 a 35 d�as entre cada entrega de sulfato ferroso o multimicronutriente CIE: Z298 (Lab: SF1...SF6 � 1�6 MN), 
y con un rango de 25 a 70 d�as entre cada entrega de polimaltosado CIE: Z298 (Lab: P01�P06 � PO1�PO6).

Denominador: Total de ni�os cumplen 544 d�as (17 meses 29 d�as) en el periodo de evaluaci�n, con SIS, sin dato de seguro 
y sin seguro (poblaci�n MINSA y Gobierno Regional), registrados en el padr�n nominal con DNI, 
seg�n el �mbito de la jurisdicci�n determinado por la residencia registrada en el padr�n nominal. 
Sin diagn�stico de anemia registrado en el HIS entre los 170 y 364 d�as de edad (11 meses 29 d�as).

Sintaxis: Suma de DNI �nicos de ni�os que cumplen 544 d�as (17 meses 29 d�as) en el mes de evaluaci�n registrados en el Padr�n Nominal con DNI y 
tipo de seguro SIS, sin seguro y sin dato (poblaci�n MINSA y Gobierno Regional). 
Sin diagn�stico definitivo o repetitivo de anemia registrado en HIS con c�digo(s) HIS= D50.0, D50.8, D50.9 o D64.9 entre los 170 y 364 d�as (11 meses y 29 d�as).

Fuente de datos	:

Numerador: HIS-MINSA.
Denominador: Padr�n nominal y HIS
Informaci�n HIS-MINSA 2021: data cerrada al 28 de febrero del 2022.
==============================================================================*/

USE BDHIS_MINSA

DROP TABLE #HIS_MINSA
DROP TABLE #2019
DROP TABLE #2020
DROP TABLE #2021
DROP TABLE #PN_DNI
DROP TABLE #PADRON
DROP TABLE #PADRON_NOMINAL
DROP TABLE #ATENDIDOS
DROP TABLE #TEMP_1
DROP TABLE #TEMP_2
DROP TABLE #TEMP_3
DROP TABLE #TEMP_4
DROP TABLE #TEMP_5
DROP TABLE #TEMP_6
DROP TABLE #TEMP_7
DROP TABLE #TEMP_8
DROP TABLE #TEMP_9
DROP TABLE #TEMP_10
DROP TABLE #TEMP_11
DROP TABLE #TEMP_12
DROP TABLE #TEMP_19
DROP TABLE #TEMP_19_1
DROP TABLE #TEMP_20
DROP TABLE #TEMP_21
DROP TABLE #TEMP_22
DROP TABLE #TEMP_23
DROP TABLE #TEMP_24
DROP TABLE #TEMP_25
DROP TABLE #PRE_COLLAPSE
DROP TABLE #COLLAPSE_NOM_1
DROP TABLE #COLLAPSE_NOM_2
DROP TABLE #DL1153_2021_02_NOMINAL
DROP TABLE #DL1153_2021_02_CONSOLIDADO
DROP TABLE #DL1153_2021_02_CONSOLIDADO_TOTAL

--=============================================================================
DROP TABLE #TRAMAHISMINSA_202106_20210720
SELECT
	N.ANIO + RIGHT('00' + N.MES, 2) AS ANIOMES,
	MP.ID_TIPO_DOCUMENTO_PACIENTE 	AS ID_TIPO_DOC,
	MP.ID_GENERO					AS ID_GENERO,
	N.CODIGO_ITEM 					AS COD_ITEM,
	N.VALOR_LAB						AS VALOR_LAB,
	N.TIPO_DIAGNOSTICO				AS ID_TIPITEM,
	ME.CODIGO_UNICO					AS RENAES,
	N.EDAD_REG,
	N.ID_CITA,

	MP.NUMERO_DOCUMENTO_PACIENTE 	AS NUM_DOC,
	N.FECHA_ATENCION 				AS FECHA_CITA,
	N.FECHA_ATENCION 				AS PERIODO,
	(MP.APELLIDO_PATERNO_PACIENTE + ' ' + MP.APELLIDO_MATERNO_PACIENTE + ' ' + MP.NOMBRES_PACIENTE) AS PACIENTE
INTO
	#TRAMAHISMINSA_202106_20210720
FROM
	NOMINAL_TRAMA_NUEVO AS N
		INNER JOIN MAESTRO_PACIENTE AS MP
			ON N.ID_PACIENTE = MP.ID_PACIENTE
		INNER JOIN MAESTRO_HIS_ESTABLECIMIENTO AS ME
			ON N.ID_ESTABLECIMIENTO = ME.ID_ESTABLECIMIENTO

--=============================================================================
DROP TABLE #PADRON_NOMINAL_30062021
SELECT
	DNI AS [NU_DNI_MENOR]
	, CNV AS NU_CNV
	, (APELLIDO_PATERNO_MENOR + ' ' + APELLIDO_MATERNO_MENOR + ' ' + NOMBRES_MENOR) AS [NIÑO PADRON]
	, FECHA_DE_NACIMIENTO_MENOR AS [FE_NAC_MENOR]
	, UBIGEO_DISTRITO AS CO_UBIGEO_INEI
	, PROVINCIA
	, DISTRITO
	, TI_DOC_IDENTIDAD = CASE	WHEN CHARINDEX('1', TIPO_DOCUMENTO, 1) != 0 THEN '1'
							WHEN CHARINDEX('3', TIPO_DOCUMENTO, 1) != 0 THEN '3'
					END
	, TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN '1'
					WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN '2'
					WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN '3'
					WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN '4'
					ELSE '9'
					END
	-- , TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN 'MINSA'
	--				 WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN 'ESSALUD'
	--				 WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN 'SANIDAD FFAA/PNP'
	--				 WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN 'PRIVADO'
	--				 ELSE 'SIN REGISTRO'
	--				 END
INTO
	#PADRON_NOMINAL_30062021
FROM
	PADRON_NOMINAL
--=============================================================================
DROP TABLE #RENAES
SELECT
	*
INTO
	#RENAES
FROM
	RENAES_20210720
--=============================================================================

DECLARE @MES_INICIO INT ,
		@MES_FINAL INT , 
		@YEAR INT

SET @MES_INICIO=1 -- <========= CAMBIAR MES INICIO
SET @MES_FINAL=6 -- <========= CAMBIAR MES FINAL
SET @YEAR=2021 -- <========= CAMBIAR AÑO.

--====================================
--    REDUCIENDO TAMA�O HIS MINSA

SELECT * INTO #2019
FROM #TRAMAHISMINSA_202106_20210720
WHERE LTRIM(RTRIM(COD_ITEM)) IN ('D500','D508','D509','D649'
				  ,'90669','90670','Z238' -- NEUMO
				  ,'90681','Z268' -- ROTA
				  ,'90712','90713','Z240' -- POLIO
				  ,'90723','Z276' -- PENTA
				  ,'90657','Z2511' -- INFLU
				  ,'90707','Z274' -- SPR
				  ,'Z001'
				  ,'Z017','85018'
				  ,'Z298','99199.17','99199.19')			  			
AND YEAR(TRY_CONVERT(DATE,PERIODO))=@YEAR-2
AND TRY_CONVERT(INT,id_tipo_doc)=1
AND len(replace(ltrim(rtrim(NUM_DOC)),LEFT(ltrim(rtrim(NUM_DOC)),1),''))>0
AND TRY_CONVERT(INT,NUM_DOC) IS NOT NULL 

SELECT * 
INTO #2020
FROM #TRAMAHISMINSA_202106_20210720 --< Versi�n final.  (Por mientras)
WHERE LTRIM(RTRIM(COD_ITEM)) IN ('D500','D508','D509','D649'
				  ,'90669','90670','Z238' -- NEUMO
				  ,'90681','Z268' -- ROTA
				  ,'90712','90713','Z240' -- POLIO
				  ,'90723','Z276' -- PENTA
				  ,'90657','Z2511' -- INFLU
				  ,'90707','Z274' -- SPR
				  ,'Z001'
				  ,'Z017','85018'
				  ,'Z298','99199.17','99199.19')					
AND YEAR(CONVERT(DATE,PERIODO))=@YEAR-1
AND TRY_CONVERT(INT,id_tipo_doc)=1
AND len(replace(ltrim(rtrim(NUM_DOC)),LEFT(ltrim(rtrim(NUM_DOC)),1),''))>0
AND TRY_CONVERT(INT,NUM_DOC) IS NOT NULL 

SELECT * 
INTO #2021
FROM #TRAMAHISMINSA_202106_20210720
WHERE LTRIM(RTRIM(COD_ITEM)) IN ('D500','D508','D509','D649'
				  ,'90669','90670','Z238' -- NEUMO
				  ,'90681','Z268' -- ROTA
				  ,'90712','90713','Z240' -- POLIO
				  ,'90723','Z276' -- PENTA
				  ,'90657','Z2511' -- INFLU
				  ,'90707','Z274' -- SPR
				  ,'Z001'
				  ,'Z017','85018'
				  ,'Z298','99199.17','99199.19')	
AND YEAR(CONVERT(DATE,PERIODO))=@YEAR AND CONVERT(INT, SUBSTRING(ANIOMES,5,2))<=@MES_FINAL
AND TRY_CONVERT(INT,id_tipo_doc)=1
AND len(replace(ltrim(rtrim(NUM_DOC)),LEFT(ltrim(rtrim(NUM_DOC)),1),''))>0
AND TRY_CONVERT(INT,NUM_DOC) IS NOT NULL 

SELECT * 
INTO #PADRON_NOMINAL
FROM #PADRON_NOMINAL_30062021
WHERE NU_DNI_MENOR IS NOT NULL  -- NO SE CONSIDERAN DOCUMENTOS NULOS 
AND NU_DNI_MENOR NOT IN ('','NULL')  -- NO SE CONSIDERAN DOCUMENTOS VACIOS. 
AND TRY_CONVERT(INT,TI_DOC_IDENTIDAD)=1 -- SE CONSIDERAN SOLO TIPO DE DOCUMENTO: DNI. 
AND len(replace(ltrim(rtrim(NU_DNI_MENOR)),LEFT(ltrim(rtrim(NU_DNI_MENOR)),1),''))>0
AND TRY_CONVERT(INT,NU_DNI_MENOR) IS NOT NULL 
--------------------------------------------

--================
-- PADRON NOMINAL 
--================

--1.1 BASE COMPLETA DE PADRON NOMINAL.
SELECT A.*
, B.diris DIRIS, CASE 
	WHEN B.DESC_DPTO='LIMA' AND B.DESC_PROV='LIMA' THEN 'LIMA METROPOLITANA'
	WHEN B.DESC_DPTO='LIMA' AND B.DESC_PROV<>'LIMA' THEN 'LIMA PROVINCIAS'
	ELSE B.DESC_DPTO END DPTO
, B.desc_prov PROV
, B.desc_dist DIST
, B.RED 
INTO #PADRON
FROM (
		SELECT CONVERT(INT,NU_DNI_MENOR) DNI
		, TI_DOC_IDENTIDAD TDOC
		, FE_NAC_MENOR FECHA_NAC
		, CO_UBIGEO_INEI UBIGEO
		, SEGURO= CASE 
			WHEN TI_SEGURO_MENOR='1' then 'MINSA'	
			WHEN TI_SEGURO_MENOR='2' then 'ESSALUD'
			WHEN TI_SEGURO_MENOR='3' then 'SANIDAD FFAA/PNP' 
			WHEN TI_SEGURO_MENOR='4' then 'PRIVADO'	
			ELSE 'SIN REGISTRO' END
			FROM #PADRON_NOMINAL
) A 
INNER JOIN
Maestro_UBIGEO_20200407 B ON CONVERT(INT,A.UBIGEO)=CONVERT(INT,B.UBIGEO) 

--1.2 REDUCCION DE PADRON NOMINAL. (NI�OS CON 544 DIAS EN MES DE EVALUACI�N) 
select * 
, AÑO=@YEAR
INTO #PN_DNI
from (
		SELECT DNI
		, TDOC
		, FECHA_NAC
		, SEGURO
		, UBIGEO
		, DPTO
		, PROV
		, DIST
		, DIRIS
		, RED 
		, MONTH(DATEADD(DD,544,FECHA_NAC)) MES 
		FROM #PADRON 
		WHERE YEAR(DATEADD(DD,544,FECHA_NAC))=@YEAR AND 
		MONTH(DATEADD(DD,544,FECHA_NAC))<=@MES_FINAL AND MONTH(DATEADD(DD,544,FECHA_NAC))>=@MES_INICIO
) AS T 

--================================
-- HIS - MINSA Y ATENDIDOS. 
--===============================

--2.1 UNION DE BASE DE HIS-MINSA
	SELECT 
	CONVERT(VARCHAR,ID_CITA) COLLATE SQL_Latin1_General_CP1_CI_AS ID_CITA
	, TRY_CONVERT(DATE,PERIODO) FECHA_ATENCION
	, NUM_DOC COLLATE SQL_Latin1_General_CP1_CI_AS DNI
	, LTRIM(RTRIM(ID_TIPITEM)) COLLATE SQL_Latin1_General_CP1_CI_AS TIPO
	, LTRIM(RTRIM(COD_ITEM)) COLLATE SQL_Latin1_General_CP1_CI_AS COD_ITEM
	, LTRIM(RTRIM(VALOR_LAB)) COLLATE SQL_Latin1_General_CP1_CI_AS VALOR_LAB 
	INTO #HIS_MINSA
	FROM #2019

	INSERT INTO #HIS_MINSA
	SELECT 
	CONVERT(VARCHAR,ID_CITA) COLLATE SQL_Latin1_General_CP1_CI_AS ID_CITA
	, CONVERT(DATE,PERIODO) FECHA_ATENCION
	, NUM_DOC COLLATE SQL_Latin1_General_CP1_CI_AS DNI
	, LTRIM(RTRIM(ID_TIPITEM)) COLLATE SQL_Latin1_General_CP1_CI_AS TIPO
	, LTRIM(RTRIM(COD_ITEM)) COLLATE SQL_Latin1_General_CP1_CI_AS COD_ITEM
	, LTRIM(RTRIM(VALOR_LAB)) COLLATE SQL_Latin1_General_CP1_CI_AS VALOR_LAB 
	FROM #2020

	INSERT INTO #HIS_MINSA
	SELECT 	
	CONVERT(VARCHAR,ID_CITA) ID_CITA
	, CONVERT(DATE,PERIODO) FECHA_ATENCION
	,  NUM_DOC COLLATE SQL_Latin1_General_CP1_CI_AS DNI
	, LTRIM(RTRIM(ID_TIPITEM)) TIPO
	, LTRIM(RTRIM(COD_ITEM)) COD_ITEM
	, LTRIM(RTRIM(VALOR_LAB)) VALOR_LAB 
	FROM #2021

--2.2 UNION DE BASE DE HIS Y BASE PADRON NOMINAL.
SELECT  A.*
, B.FECHA_ATENCION
, B.ID_CITA
, B.TIPO
, B.COD_ITEM
, B.VALOR_LAB
INTO #ATENDIDOS 
FROM #PN_DNI A 
LEFT JOIN 
#HIS_MINSA B ON TRY_CONVERT(INT,A.DNI)=TRY_CONVERT(INT,B.DNI) 

--================================================================
--                      INDICADORES 
--================================================================

-----------------------------
-- 3.1 DENOMINADOR. 
-----------------------------

---- 3.1.1 SIN DIAGNOSTICO DEFINITIVO O REPETITIVO DE ANEMIA. 
SELECT *
, IIF(FECHA_DX IS NULL,1,0) DEN 
INTO #TEMP_1
FROM(
		SELECT *
		, MAX(TEMP_FECHA_DX) OVER (PARTITION BY DNI) FECHA_DX
		FROM (
				SELECT *
				,IIF(COD_ITEM IN ('D500','D508','D509','D649') 
				AND TIPO IN ('D','R')
				AND FECHA_ATENCION IS NOT NULL
				AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=170 
				AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=364,FECHA_ATENCION,NULL) TEMP_FECHA_DX
				FROM #ATENDIDOS
		) AS T1 
) AS T0

--------------------------------
-- 3.2 NUMERADOR.
-------------------------------

----- 3.2.1 VACUNAS. [ESQUEMA DE 2021 - SEGUN LA FICHA]

----------- A. POLIO
SELECT *
, IIF(VAC_POLIO_1 IS NOT NULL AND DEN=1,1,0) POLIO_1
, IIF(VAC_POLIO_2 IS NOT NULL AND DEN=1,1,0) POLIO_2
, IIF(VAC_POLIO_3 IS NOT NULL AND DEN=1,1,0) POLIO_3
, IIF(VAC_POLIO_1 IS NOT NULL AND VAC_POLIO_2 IS NOT NULL AND VAC_POLIO_3 IS NOT NULL AND DEN=1,1,0) POLIO
INTO #TEMP_2
FROM (
	SELECT *
	, MIN(TEMP_VAC_POLIO_3) OVER (PARTITION BY DNI) VAC_POLIO_3
	FROM (
			SELECT *
			, IIF(COD_ITEM IN  ('90712','90713','Z240')AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_POLIO_2 IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,VAC_POLIO_2,FECHA_ATENCION)>=28 
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_POLIO_3
			FROM (
					SELECT *
					, MIN(TEMP_VAC_POLIO_2) OVER (PARTITION BY DNI) VAC_POLIO_2
					FROM(
							SELECT *
							, IIF(COD_ITEM IN  ('90712','90713','Z240') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_POLIO_1 IS NOT NULL AND FECHA_NAC IS NOT NULL
							AND DATEDIFF(DD,VAC_POLIO_1,FECHA_ATENCION)>=28 
							AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_POLIO_2
							FROM (
									SELECT *
									, MIN(TEMP_VAC_POLIO_1) OVER (PARTITION BY DNI) VAC_POLIO_1
									FROM(
											SELECT *
											, IIF(COD_ITEM IN  ('90712','90713','Z240') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_POLIO_1
											FROM #TEMP_1
									) AS T0
							) AS T1
					) AS T2
			) AS T3
	) AS T4
) AS T5

----------- B. PENTA
SELECT *
, IIF(VAC_PENTA_1 IS NOT NULL AND DEN=1,1,0) PENTA_1
, IIF(VAC_PENTA_2 IS NOT NULL AND DEN=1,1,0) PENTA_2
, IIF(VAC_PENTA_3 IS NOT NULL AND DEN=1,1,0) PENTA_3
, IIF(VAC_PENTA_1 IS NOT NULL AND VAC_PENTA_2 IS NOT NULL AND VAC_PENTA_3 IS NOT NULL AND DEN=1,1,0) PENTA
INTO #TEMP_3
FROM (
	SELECT *
	, MIN(TEMP_VAC_PENTA_3) OVER (PARTITION BY DNI) VAC_PENTA_3
	FROM (
			SELECT *
			, IIF(COD_ITEM IN  ('90723','Z276') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_PENTA_2 IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,VAC_PENTA_2,FECHA_ATENCION)>=28 
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_PENTA_3
			FROM (
					SELECT *
					, MIN(TEMP_VAC_PENTA_2) OVER (PARTITION BY DNI) VAC_PENTA_2
					FROM(
							SELECT *
							, IIF(COD_ITEM IN  ('90723','Z276')  AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_PENTA_1 IS NOT NULL AND FECHA_NAC IS NOT NULL
							AND DATEDIFF(DD,VAC_PENTA_1,FECHA_ATENCION)>=28 
							AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_PENTA_2
							FROM (
									SELECT *
									, MIN(TEMP_VAC_PENTA_1) OVER (PARTITION BY DNI) VAC_PENTA_1
									FROM(
											SELECT *
											, IIF(COD_ITEM IN  ('90723','Z276')  AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_PENTA_1
											FROM #TEMP_2
									) AS T0
							) AS T1
					) AS T2
			) AS T3
	) AS T4
) AS T5

----------- C. NEUMO 
SELECT *
, IIF(VAC_NEUMO_1 IS NOT NULL AND DEN=1,1,0) NEUMO_1
, IIF(VAC_NEUMO_2 IS NOT NULL AND DEN=1,1,0) NEUMO_2
, IIF(VAC_NEUMO_3 IS NOT NULL AND DEN=1,1,0) NEUMO_3
, IIF(VAC_NEUMO_1 IS NOT NULL AND VAC_NEUMO_2 IS NOT NULL AND VAC_NEUMO_3 IS NOT NULL AND DEN=1,1,0) NEUMO
INTO #TEMP_4
FROM (
	SELECT *
	, MIN(TEMP_VAC_NEUMO_3) OVER (PARTITION BY DNI) VAC_NEUMO_3
	FROM (
			SELECT *
			, IIF(COD_ITEM IN ('90669','90670','Z238')  AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_NEUMO_2 IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,VAC_NEUMO_2,FECHA_ATENCION)>=28 
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_NEUMO_3
			FROM (
					SELECT *
					, MIN(TEMP_VAC_NEUMO_2) OVER (PARTITION BY DNI) VAC_NEUMO_2
					FROM(
							SELECT *
							, IIF(COD_ITEM IN ('90669','90670','Z238')  AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_NEUMO_1 IS NOT NULL AND FECHA_NAC IS NOT NULL
							AND DATEDIFF(DD,VAC_NEUMO_1,FECHA_ATENCION)>=28 
							AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_NEUMO_2
							FROM (
									SELECT *
									, MIN(TEMP_VAC_NEUMO_1) OVER (PARTITION BY DNI) VAC_NEUMO_1
									FROM(
											SELECT *
											, IIF(COD_ITEM IN ('90669','90670','Z238')  AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60
											AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_NEUMO_1
											FROM #TEMP_3
									) AS T0
							) AS T1
					) AS T2
			) AS T3
	) AS T4
) AS T5

----------- D. ROTA
SELECT *
, IIF(VAC_ROTA_1 IS NOT NULL AND DEN=1,1,0) ROTA_1
, IIF(VAC_ROTA_2 IS NOT NULL AND DEN=1,1,0) ROTA_2
, IIF(VAC_ROTA_1 IS NOT NULL AND VAC_ROTA_2 IS NOT NULL AND DEN=1,1,0) ROTA
INTO #TEMP_5
FROM (
		SELECT *
		, MIN(TEMP_VAC_ROTA_2) OVER (PARTITION BY DNI) VAC_ROTA_2
		FROM(
				SELECT *
				, IIF(COD_ITEM IN ('90681','Z268') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND VAC_ROTA_1 IS NOT NULL AND FECHA_NAC IS NOT NULL
				AND DATEDIFF(DD,VAC_ROTA_1,FECHA_ATENCION)>=28 
				AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=239,FECHA_ATENCION,NULL) TEMP_VAC_ROTA_2
				FROM (
						SELECT *
						, MIN(TEMP_VAC_ROTA_1) OVER (PARTITION BY DNI) VAC_ROTA_1
						FROM(
								SELECT *
								, IIF(COD_ITEM IN ('90681','Z268') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
								AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60 
								AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=239,FECHA_ATENCION,NULL) TEMP_VAC_ROTA_1
								FROM #TEMP_4
						) AS T0
				) AS T1
		) AS T2
) AS T3

----------- E. INFLUENZA 
SELECT *
, IIF(VAC_INFLU IS NOT NULL AND DEN=1,1,0) INFLU
INTO #TEMP_6
FROM (
	SELECT *
	, MIN(TEMP_VAC_INFLU) OVER (PARTITION BY DNI) VAC_INFLU
	FROM(
			SELECT *
			, IIF(COD_ITEM IN ('90657','Z2511') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_INFLU
			FROM #TEMP_5
	) AS T0
) AS T1

----------- F. SPR
SELECT *
, IIF(VAC_SPR IS NOT NULL AND DEN=1,1,0) SPR
INTO #TEMP_7
FROM (
	SELECT *
	, MIN(TEMP_VAC_SPR) OVER (PARTITION BY DNI) VAC_SPR
	FROM(
			SELECT *
			, IIF(COD_ITEM IN ('90707','Z274' ) AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=454,FECHA_ATENCION,NULL) TEMP_VAC_SPR
			FROM #TEMP_6
	) AS T0
) AS T1

----- 3.2.2 CRED.

------- 1. CONTROL 
SELECT *
, MAX(TEMP_CRED1) OVER (PARTITION BY DNI) CRED1 
INTO #TEMP_8
FROM (
		SELECT *
		, IIF(COD_ITEM IN ('Z001') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=29 
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=59, 1,0) TEMP_CRED1 
		FROM #TEMP_7
) AS T 
------- 2. CONTROL 
SELECT *
, MAX(TEMP_CRED2) OVER (PARTITION BY DNI) CRED2
INTO #TEMP_9
FROM (
		SELECT *
		, IIF(COD_ITEM IN ('Z001') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=60 
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=119, 1,0) TEMP_CRED2 
		FROM #TEMP_8
) AS T 
------- 3. CONTROL 
SELECT *
, MAX(TEMP_CRED3) OVER (PARTITION BY DNI) CRED3
INTO #TEMP_10
FROM (
		SELECT *
		, IIF(COD_ITEM IN ('Z001') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=120
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=179, 1,0) TEMP_CRED3
		FROM #TEMP_9
) AS T 
------- 4. CONTROL 
SELECT *
, MAX(TEMP_CRED4) OVER (PARTITION BY DNI) CRED4
INTO #TEMP_11
FROM (
		SELECT *
		, IIF(COD_ITEM IN ('Z001') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=180
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=269, 1,0) TEMP_CRED4
		FROM #TEMP_10
) AS T 
------- 5. CONTROL 
SELECT *
, MAX(TEMP_CRED5) OVER (PARTITION BY DNI) CRED5
INTO #TEMP_12
FROM (
		SELECT *
		, IIF(COD_ITEM IN ('Z001') AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=270
			AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=364, 1,0) TEMP_CRED5
		FROM #TEMP_11
) AS T 

----- 3.2.3 DOSAJE DE HEMOGLOBINA 
SELECT *
, IIF(FECHA_DOSAJE IS NOT NULL AND DEN=1,1,0) DOSAJE 
INTO #TEMP_19
FROM (
		SELECT *
		, MIN(TEMP_DOSAJE) OVER (PARTITION BY DNI) FECHA_DOSAJE
		FROM (
				SELECT *
				, IIF(COD_ITEM IN ('Z017','85018') AND TIPO='D' AND DEN=1 AND FECHA_ATENCION IS NOT NULL AND FECHA_NAC IS NOT NULL
					AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)>=170
					AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENCION)<=269, FECHA_ATENCION,NULL) TEMP_DOSAJE
				FROM #TEMP_12
		) AS T0
) AS T1 

----- 3.2.4 SUPLEMENTACION. 
-----***** GENERO VARIABLE DE SF,MN, PO**************************
SELECT * 
, IIF(COD_ITEM in ('Z298','99199.17') AND VALOR_LAB IN ('SF1','SF2','SF3','SF4','SF5','SF6','SF7','SF8','SF9','S10','S11','S12'),1,0) SUPLE_SF
, IIF(COD_ITEM in ('Z298','99199.19') AND TRY_CONVERT(INT,VALOR_LAB) IN ('1','2','3','4','5','6','7','8','9','10','11','12'),1,0) SUPLE_MN
, IIF(COD_ITEM in ('Z298','99199.17') AND VALOR_LAB IN  ('P01','P02','P03','P04','P05','P06','P07','P08','P09','P10','P11','P12','PO1','PO2','PO3','PO4','PO5','PO6','PO7','PO8','PO9'),1,0) SUPLE_PO
INTO #TEMP_19_1
FROM #TEMP_19

-------- 3.2.4.1 SUPLEMENTACION INICIAL. 
SELECT *
, MAX(IIF(FECHA_SUPLE_INICIAL  IS NOT NULL,TEMP0,NULL)) OVER (PARTITION BY DNI) SUPLE_INICIAL
INTO #TEMP_20 
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_0 IS NOT NULL AND FECHA_SUPLE_INICIAL IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_0=FECHA_SUPLE_INICIAL,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP0
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_0) OVER (PARTITION BY DNI) FECHA_SUPLE_INICIAL 
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND FECHA_DOSAJE IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_DOSAJE,FECHA_ATENCION)>=0
								AND DATEDIFF(DD,FECHA_DOSAJE,FECHA_ATENCION)<=7, FECHA_ATENCION,NULL) TEMP_FECHA_0
						FROM #TEMP_19_1
				) AS T0
		) AS T1
) AS T2

-------- 3.2.4.2 CONTINUACION DURANTE 6 MESES DE SUPLEMENTACION CON SULFATO FERROSO O MULTIMICRONUETRIENTES O POLIMALTOSADO.

--1. 
SELECT *
, MAX(IIF(FECHA_SUPLE_1 IS NOT NULL,TEMP1,NULL)) OVER (PARTITION BY DNI) SUPLE_1
INTO #TEMP_21
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_1 IS NOT NULL AND FECHA_SUPLE_1 IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_1=FECHA_SUPLE_1,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP1
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_1) OVER (PARTITION BY DNI) FECHA_SUPLE_1
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND SUPLE_INICIAL IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND FECHA_SUPLE_INICIAL IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_SUPLE_INICIAL,FECHA_ATENCION)>=25
								AND DATEDIFF(DD,FECHA_SUPLE_INICIAL,FECHA_ATENCION)<(35*SUPLE_INICIAL),FECHA_ATENCION,NULL) TEMP_FECHA_1
						FROM #TEMP_20
				) AS T0
		) AS T1
) AS T2

--2. 
SELECT *
, MAX(IIF(FECHA_SUPLE_2 IS NOT NULL,TEMP2,NULL)) OVER (PARTITION BY DNI) SUPLE_2
INTO #TEMP_22
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_2 IS NOT NULL AND FECHA_SUPLE_2 IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_2=FECHA_SUPLE_2,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP2
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_2) OVER (PARTITION BY DNI) FECHA_SUPLE_2
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND SUPLE_1 IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND FECHA_SUPLE_1 IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_SUPLE_1,FECHA_ATENCION)>=25
								AND DATEDIFF(DD,FECHA_SUPLE_1,FECHA_ATENCION)<(35*SUPLE_1),FECHA_ATENCION,NULL) TEMP_FECHA_2
						FROM #TEMP_21
				) AS T0
		) AS T1
) AS T2

--3. 
SELECT *
, MAX(IIF(FECHA_SUPLE_3 IS NOT NULL,TEMP3,NULL)) OVER (PARTITION BY DNI) SUPLE_3
INTO #TEMP_23
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_3 IS NOT NULL AND FECHA_SUPLE_3 IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_3=FECHA_SUPLE_3,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP3
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_3) OVER (PARTITION BY DNI) FECHA_SUPLE_3
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND SUPLE_2 IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND FECHA_SUPLE_2 IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_SUPLE_2,FECHA_ATENCION)>=25
								AND DATEDIFF(DD,FECHA_SUPLE_2,FECHA_ATENCION)<(35*SUPLE_2),FECHA_ATENCION,NULL) TEMP_FECHA_3
						FROM #TEMP_22
				) AS T0
		) AS T1
) AS T2

--4. 
SELECT *
, MAX(IIF(FECHA_SUPLE_4 IS NOT NULL,TEMP4,NULL)) OVER (PARTITION BY DNI) SUPLE_4
INTO #TEMP_24
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_4 IS NOT NULL AND FECHA_SUPLE_4 IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_4=FECHA_SUPLE_4,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP4
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_4) OVER (PARTITION BY DNI) FECHA_SUPLE_4
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND SUPLE_3 IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND FECHA_SUPLE_3 IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_SUPLE_3,FECHA_ATENCION)>=25
								AND DATEDIFF(DD,FECHA_SUPLE_3,FECHA_ATENCION)<(35*SUPLE_3),FECHA_ATENCION,NULL) TEMP_FECHA_4
						FROM #TEMP_23
				) AS T0
		) AS T1
) AS T2

--5. 
SELECT *
, MAX(IIF(FECHA_SUPLE_5 IS NOT NULL,TEMP5,NULL)) OVER (PARTITION BY DNI) SUPLE_5
INTO #TEMP_25
FROM(
		SELECT * 
		, IIF(TEMP_FECHA_5 IS NOT NULL AND FECHA_SUPLE_5 IS NOT NULL AND DEN=1
		,IIF(TEMP_FECHA_5=FECHA_SUPLE_5,1,0)+IIF(SUPLE_PO=1,1,0),NULL) TEMP5
		FROM (
				SELECT *
				, MIN(TEMP_FECHA_5) OVER (PARTITION BY DNI) FECHA_SUPLE_5
				FROM (
						SELECT *
						, IIF((SUPLE_SF=1 OR SUPLE_MN=1 OR SUPLE_PO=1)
								AND SUPLE_4 IS NOT NULL AND FECHA_ATENCION IS NOT NULL AND FECHA_SUPLE_4 IS NOT NULL AND DEN=1
								AND DATEDIFF(DD,FECHA_SUPLE_4,FECHA_ATENCION)>=25
								AND DATEDIFF(DD,FECHA_SUPLE_4,FECHA_ATENCION)<(35*SUPLE_4),FECHA_ATENCION,NULL) TEMP_FECHA_5
						FROM #TEMP_24
				) AS T0
		) AS T1
) AS T2

-------- 3.2.4.3 SUPLEMENTACION FINAL.
SELECT *
, IIF(SUPLE_INICIAL IS NULL,0,SUPLE_INICIAL) TIPO_SUPLE_0
, IIF(SUPLE_1 IS NULL,0,SUPLE_1) TIPO_SUPLE_1
, IIF(SUPLE_2 IS NULL,0,SUPLE_2) TIPO_SUPLE_2
, IIF(SUPLE_3 IS NULL,0,SUPLE_3) TIPO_SUPLE_3
, IIF(SUPLE_4 IS NULL,0,SUPLE_4) TIPO_SUPLE_4
, IIF(SUPLE_5 IS NULL,0,SUPLE_5) TIPO_SUPLE_5
INTO #PRE_COLLAPSE
FROM #TEMP_25

--========================
-- COLLAPSE
--========================
SELECT 
DNI, SEGURO, UBIGEO, DPTO , PROV, DIST, DIRIS, RED, AÑO, MES
, MAX(DEN) DEN
-- VACUNAS
, MAX(POLIO) POLIO, MAX( POLIO_1) POLIO_1, MAX(POLIO_2) POLIO_2, MAX(POLIO_3) POLIO_3
, MAX(PENTA) PENTA, MAX(PENTA_1) PENTA_1, MAX(PENTA_2) PENTA_2, MAX(PENTA_3) PENTA_3
, MAX(NEUMO) NEUMO, MAX(NEUMO_1) NEUMO_1, MAX(NEUMO_2) NEUMO_2, MAX(NEUMO_3) NEUMO_3
, MAX(ROTA) ROTA, MAX(ROTA_1) ROTA_1, MAX(ROTA_2) ROTA_2
, MAX(SPR) SPR, MAX(INFLU) INFLU
-- CRED
, MAX(CRED1) CRED1, MAX(CRED2) CRED2, MAX(CRED3) CRED3, MAX(CRED4) CRED4, MAX(CRED5) CRED5
-- DOSAJE
, MAX(DOSAJE) DOSAJE
--SUPLE
, MAX(TIPO_SUPLE_0) TIPO_SUPLE_0 , MAX(TIPO_SUPLE_1) TIPO_SUPLE_1 , MAX(TIPO_SUPLE_2) TIPO_SUPLE_2 
, MAX(TIPO_SUPLE_3) TIPO_SUPLE_3 , MAX(TIPO_SUPLE_4) TIPO_SUPLE_4 , MAX(TIPO_SUPLE_5) TIPO_SUPLE_5 
INTO #COLLAPSE_NOM_1 
FROM #PRE_COLLAPSE
GROUP BY DNI, SEGURO, UBIGEO, DPTO , PROV, DIST, DIRIS, RED, AÑO, MES

--CONTEO (VACUNAS , CRED, DOSAJE Y SUPLEMENTACION) 
SELECT *
, IIF(VAL_VAC=6 AND DEN=1,1,0) NUM_VAC
, IIF(VAL_CRED=5 AND DEN=1,1,0) NUM_CRED
, IIF(DOSAJE=1 AND DEN=1,1,0) NUM_DOZAJE
, IIF(VAL_SUPLE>=6 AND DEN=1,1,0) NUM_SUPLE
INTO #COLLAPSE_NOM_2
FROM (
		SELECT * 
		, POLIO+PENTA+NEUMO+INFLU+ROTA+SPR VAL_VAC
		, CRED1+CRED2+CRED3+CRED4+CRED5 VAL_CRED
		, TIPO_SUPLE_0+TIPO_SUPLE_1+TIPO_SUPLE_2+TIPO_SUPLE_3+TIPO_SUPLE_4+TIPO_SUPLE_5 VAL_SUPLE
		FROM #COLLAPSE_NOM_1
) AS T

--===================
-- BASE FINAL 
--===================

--NUMERADORES.
SELECT *
, IIF(NUM_VAC=1 AND NUM_CRED=1 AND NUM_DOZAJE=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM
, IIF(NUM_VAC=1 AND NUM_CRED=1 AND NUM_DOZAJE=1 AND DEN=1,1,0) NUM_VCD
, IIF(NUM_VAC=1 AND NUM_CRED=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_VCS
, IIF(NUM_VAC=1 AND NUM_DOZAJE=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_VDS
, IIF(NUM_CRED=1 AND NUM_DOZAJE=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_CDS
, IIF(NUM_VAC=1 AND NUM_CRED=1 AND DEN=1,1,0) NUM_VC
, IIF(NUM_VAC=1 AND NUM_DOZAJE=1 AND DEN=1,1,0) NUM_VD
, IIF(NUM_VAC=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_VS
, IIF(NUM_CRED=1 AND NUM_DOZAJE=1 AND DEN=1,1,0) NUM_CD
, IIF(NUM_CRED=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_CS
, IIF(NUM_DOZAJE=1 AND NUM_SUPLE=1 AND DEN=1,1,0) NUM_DS
INTO #DL1153_2021_02_NOMINAL
FROM #COLLAPSE_NOM_2

--*********************************************************************************************************************************
-- CALCULO DE NOMINALES
--*********************************************************************************************************************************
SELECT
	N.*
	, MES = case
when N.mes=1 then 'ENERO'
when N.mes=2 then 'FEBRERO'
when N.mes=3 then 'MARZO'
when N.mes=4 then 'ABRIL'
when N.mes=5 then 'MAYO'
when N.mes=6 then 'JUNIO'
when N.mes=7 then 'JULIO' 
when N.mes=8 then 'AGOSTO'
when N.mes=9 then 'SETIEMBRE'
when N.mes=10 then 'OCTUBRE'
when N.mes=11 then 'NOVIEMBRE'
when N.mes=12 then 'DICIEMBRE' end
	, P.[NIÑO PADRON]
FROM
	#DL1153_2021_02_NOMINAL AS N
		LEFT JOIN #PADRON_NOMINAL AS P
			ON N.DNI = P.NU_DNI_MENOR
--*********************************************************************************************************************************

-- COLLAPSE FINAL 
SELECT 
UBIGEO, SEGURO, DPTO DEPARTAMENTO, PROV PROVINCIA, DIST DISTRITO, DIRIS, RED, MES, AÑO
, SUM(DEN) DENOMINADOR  , SUM(NUM) NUMERADOR, COUNT(DNI) PADRON 
, SUM(NUM_VAC) NUM_VAC, SUM(NUM_CRED) NUM_cRED, SUM(NUM_DOZAJE) NUM_DOZAJE, SUM(NUM_SUPLE) NUM_SUPLE
, SUM(NUM_VCD) NUM_VCD, SUM(NUM_VCS) NUM_VCS, SUM(NUM_VDS) NUM_VDS, SUM(NUM_CDS) NUM_CDS
, SUM(NUM_VC) NUM_VC, SUM(NUM_VD) NUM_VD, SUM(NUM_VS) NUM_VS, SUM(NUM_CD) NUM_CD, SUM(NUM_CS) NUM_cS, SUM(NUM_DS) NUM_DS
-- VACUNAS
, SUM(POLIO) POLIO, SUM( POLIO_1) POLIO_1, SUM(POLIO_2) POLIO_2, SUM(POLIO_3) POLIO_3
, SUM(PENTA) PENTA, SUM(PENTA_1) PENTA_1, SUM(PENTA_2) PENTA_2, SUM(PENTA_3) PENTA_3
, SUM(NEUMO) NEUMO, SUM(NEUMO_1) NEUMO_1, SUM(NEUMO_2) NEUMO_2, SUM(NEUMO_3) NEUMO_3
, SUM(ROTA) ROTA, SUM(ROTA_1) ROTA_1, SUM(ROTA_2) ROTA_2
, SUM(SPR) SPR, SUM(INFLU) INFLU
-- CRED
, SUM(CRED1) CRED1, SUM(CRED2) CRED2, SUM(CRED3) CRED3, SUM(CRED4) CRED4, SUM(CRED5) CRED5
-- DOSAJE
, SUM(DOSAJE) DOSAJE
--SUPLE
, SUM(TIPO_SUPLE_0) TIPO_SUPLE_O , SUM(TIPO_SUPLE_1) TIPO_SUPLE_1 , SUM(TIPO_SUPLE_2) TIPO_SUPLE_2 
, SUM(TIPO_SUPLE_3) TIPO_SUPLE_3 , SUM(TIPO_SUPLE_4) TIPO_SUPLE_4 , SUM(TIPO_SUPLE_5) TIPO_SUPLE_5
INTO #DL1153_2021_02_CONSOLIDADO_TOTAL
FROM #DL1153_2021_02_NOMINAL
GROUP BY 
UBIGEO, SEGURO, DPTO, PROV, DIST, DIRIS, RED, MES, AÑO


SELECT RIGHT('000000'+RTRIM(LTRIM(UBIGEO)),6) UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DIRIS, RED, SEGURO, AÑO
,MES= case
when mes=1 then 'ENERO'
when mes=2 then 'FEBRERO'
when mes=3 then 'MARZO'
when mes=4 then 'ABRIL'
when mes=5 then 'MAYO'
when mes=6 then 'JUNIO'
when mes=7 then 'JULIO' 
when mes=8 then 'AGOSTO'
when mes=9 then 'SETIEMBRE'
when mes=10 then 'OCTUBRE'
when mes=11 then 'NOVIEMBRE'
when mes=12 then 'DICIEMBRE' end
, DENOMINADOR, NUMERADOR, PADRON, NUM_VAC, NUM_CRED, NUM_DOZAJE, NUM_SUPLE, NUM_VCD, NUM_VCS, NUM_VDS, NUM_CDS, NUM_VC, NUM_VD, NUM_VS, NUM_CD, NUM_CS, NUM_DS
INTO #DL1153_2021_02_CONSOLIDADO
FROM #DL1153_2021_02_CONSOLIDADO_TOTAL

SELECT * FROM #DL1153_2021_02_CONSOLIDADO