/*==============================================================================
	Indicadores DL1153

Nombre: Porcentaje de ni�as y ni�os de 4 meses de edad que inician suplementaci�n con gotas de hierro

Numerador: Ni�as y ni�os del denominador, que han recibido gotas con hierro 

Sintaxis: Suma de DNI o CNV del denominador que cumplen con el registro CIE/CPT: Z298 (Lab: SF1...SF5 � P01�P05 � PO1�PO5).

Denominador: Ni�as y ni�os que, en el per�odo de evaluaci�n, acuden al establecimiento de salud por cualquier motivo de consulta durante sus 04 meses de edad (entre los 110 y 149 d�as de edad), 
registrados con DNI o CNV en HIS. 

Sintaxis: Suma de DNI o CNV �nicos de ni�as y ni�os que, en el per�odo de evaluaci�n, acuden al establecimiento de salud por cualquier motivo de consulta durante 
sus 04 meses de edad (entre los 110 y 149 d�as de edad),
registrados con DNI en HIS.

(HAY 3 OPCIONES CRITERIO PARA EL DENOMINADOR Y NUMERADOR) 
	- SI EL NI�O VISITO 3 EESS Y UNO ENTREGO GOTAS (SOLO SE CONSIDERA AL EESS QUE ENTREGO LAS GOTAS).
	- SI EL NI�O VISITA 3 EESS Y 2 ENTREGAN GOTAS (SOLO SE CONSIDERA AL EESS QUE ENTREGO LAS GOTAS PRIMERO). 
	- SI EL NI�O VISITO 3 EEES Y NI UNO ENTREGO GOTAS (SE PENALIZA A TODOS Y SE LES CONSIDERA A TODOS EN EL DENOMINADOR). 

Fuente: HIS
�mbito de medici�n: IPRESS.
Periodicidad: Mensual
==============================================================================*/

use BDHIS_MINSA
go

 DROP TABLE #TRAMA_HIS
 DROP TABLE #TRAMAHIS
 DROP TABLE #TEMP3_GOTAS
 DROP TABLE #TEMP3_NOGOTAS
 DROP TABLE #HIS_MINSA
 DROP TABLE #2019
 DROP TABLE #2020
 DROP TABLE #2021
 DROP TABLE #PN_DNI
 DROP TABLE #PADRON
 DROP TABLE #BPN
 DROP TABLE #PADRON_03
 DROP TABLE #PADRONF_03
 DROP TABLE #PADRON_NOMINAL
 DROP TABLE #ATENDIDOS
 DROP TABLE #TMP_1
 DROP TABLE #TMP_01
 DROP TABLE #TMP_02
 DROP TABLE #TMP_2
 DROP TABLE #TMP_3
 DROP TABLE #TMP_4
 DROP TABLE #CRED1_03
 DROP TABLE #CRED2_03
 DROP TABLE #TEMP1
 DROP TABLE #TEMP2
 DROP TABLE #TEMP3
 DROP TABLE #TEMP4
 DROP TABLE #TEMP_5
 DROP TABLE #TEMP_6
 DROP TABLE #TEMP_7
 DROP TABLE #TEMP_8
 DROP TABLE #TEMP_9
 DROP TABLE #TEMP_10
 DROP TABLE #TEMP_11
 DROP TABLE #TEMP_12
 DROP TABLE #TEMP_19
 DROP TABLE #TEMP_19_1
 DROP TABLE #TEMP_20
 DROP TABLE #TEMP_21
 DROP TABLE #TEMP_22
 DROP TABLE #TEMP_23
 DROP TABLE #TEMP_24
 DROP TABLE #TEMP_25
 DROP TABLE #PRE_COLLAPSE
 DROP TABLE #COLLAPSE_FINAL
 DROP TABLE #COLLAPSE2
 DROP TABLE #DL1153_2020_04_NOMINAL
 DROP TABLE #DL1153_2020_04_CONSOLIDADO
 DROP TABLE #TRAMAHIS_CG_03_CONSOLIDADO
 DROP TABLE #TRAMAHIS_CG_03_NOMINAL

--=============================================================================
 DROP TABLE #TRAMAHISMINSA_202106_20210720
SELECT
	N.ANIO + RIGHT('00' + N.MES, 2) AS ANIOMES,
	MP.ID_TIPO_DOCUMENTO_PACIENTE 	AS ID_TIPO_DOC,
	MP.ID_GENERO					AS ID_GENERO,
	N.CODIGO_ITEM 					AS COD_ITEM,
	N.VALOR_LAB						AS VALOR_LAB,
	N.TIPO_DIAGNOSTICO				AS ID_TIPITEM,
	ME.CODIGO_UNICO					AS RENAES,
	N.EDAD_REG,
	N.ID_CITA,
	N.FECHA_REGISTRO,

	MP.NUMERO_DOCUMENTO_PACIENTE 	AS NUM_DOC,
	N.FECHA_ATENCION 				AS FECHA_CITA,
	N.FECHA_ATENCION 				AS PERIODO,
	(MP.APELLIDO_PATERNO_PACIENTE + ' ' + MP.APELLIDO_MATERNO_PACIENTE + ' ' + MP.NOMBRES_PACIENTE) AS PACIENTE
INTO
	#TRAMAHISMINSA_202106_20210720
FROM
	NOMINAL_TRAMA_NUEVO AS N
		INNER JOIN MAESTRO_PACIENTE AS MP
			ON N.ID_PACIENTE = MP.ID_PACIENTE
		INNER JOIN MAESTRO_HIS_ESTABLECIMIENTO AS ME
			ON N.ID_ESTABLECIMIENTO = ME.ID_ESTABLECIMIENTO

--=============================================================================
 DROP TABLE #PADRON_NOMINAL_30062021
SELECT
	DNI AS [NU_DNI_MENOR]
	, CNV AS NU_CNV
	, (APELLIDO_PATERNO_MENOR + ' ' + APELLIDO_MATERNO_MENOR + ' ' + NOMBRES_MENOR) AS [NIÑO PADRON]
	, FECHA_DE_NACIMIENTO_MENOR AS [FE_NAC_MENOR]
	, UBIGEO_DISTRITO AS CO_UBIGEO_INEI
	, PROVINCIA
	, DISTRITO
	, TI_DOC_IDENTIDAD = CASE	WHEN CHARINDEX('1', TIPO_DOCUMENTO, 1) != 0 THEN '1'
							WHEN CHARINDEX('3', TIPO_DOCUMENTO, 1) != 0 THEN '3'
					END
	, TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN '1'
					WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN '2'
					WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN '3'
					WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN '4'
					ELSE '9'
					END
	-- , TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN 'MINSA'
	--				 WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN 'ESSALUD'
	--				 WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN 'SANIDAD FFAA/PNP'
	--				 WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN 'PRIVADO'
	--				 ELSE 'SIN REGISTRO'
	--				 END
INTO
	#PADRON_NOMINAL_30062021
FROM
	PADRON_NOMINAL
--=============================================================================
 DROP TABLE #RENAES
SELECT
	*
INTO
	#RENAES
FROM
	RENAES_20210720
--=============================================================================

DECLARE @MES_INICIO INT ,
		@MES_FINAL INT , 
		@YEAR INT

SET @MES_INICIO=1 -- <========= CAMBIAR MES INICIO
SET @MES_FINAL=6 -- <========= CAMBIAR MES FINAL
SET @YEAR=2021 -- <========= CAMBIAR AÑO.

-- **** CAMBIAR BASE DE DATOS ACTUALIZADAS **** 
------------------------------------------------------------------------------------
-- REDUCIENDO BASE DE DATOS.
SELECT 
	CONVERT(VARCHAR,ID_CITA) ID_CITA
	, RENAES
	, CONVERT(DATE,PERIODO) FECHA_ATENCION
	, fecha_registro FECHA_REGISTRO
	, NUM_DOC DOC
	, LTRIM(RTRIM(ID_TIPITEM)) TIPO
	, LTRIM(RTRIM(COD_ITEM)) COD_ITEM
	, LTRIM(RTRIM(VALOR_LAB)) VALOR_LAB 
INTO #TRAMAHIS
FROM #TRAMAHISMINSA_202106_20210720
WHERE YEAR(CONVERT(DATE,PERIODO))=@YEAR AND MONTH(CONVERT(DATE,PERIODO))<=@MES_FINAL
AND TRY_CONVERT(INT,id_tipo_doc)=1
AND len(replace(ltrim(rtrim(NUM_DOC)),LEFT(ltrim(rtrim(NUM_DOC)),1),''))>0
AND TRY_CONVERT(INT,NUM_DOC) IS NOT NULL 

SELECT *
INTO #PADRON 
FROM (
		SELECT *, NU_DNI_MENOR DOC
		FROM #PADRON_NOMINAL_30062021
		WHERE TRY_CONVERT(INT,TI_DOC_IDENTIDAD)=1 
) AS T
WHERE DOC IS NOT NULL  -- NO SE CONSIDERAN DOCUMENTOS NULOS 
AND DOC NOT IN ('','NULL')  -- NO SE CONSIDERAN DOCUMENTOS VACIOS. 
AND len(replace(ltrim(rtrim(DOC)),LEFT(ltrim(rtrim(DOC)),1),''))>0
AND TRY_CONVERT(INT,DOC) IS NOT NULL 
AND FE_NAC_MENOR IS NOT NULL

-- SELECT *
-- INTO #RENAES 
-- FROM Renaes_20210720
------------------------------------------------------------------------------------

--==================================
-- �HIS MINSA Y PADRON NOMINAL.
--==================================

-- ATENCION ENTRE LOS 110 Y 149 DIAS DE NACIDOS. 
SELECT *
INTO #TEMP1
FROM (
	SELECT A.*
	, B.FE_NAC_MENOR FECHA_NACIMIENTO
	, DATEDIFF(DD,B.FE_NAC_MENOR,A.FECHA_ATENCION) EDAD_DIAS
	, DEN=1 
	, MONTH(A.FECHA_ATENCION) MES
	, YEAR(A.FECHA_ATENCION) AÑO
	, IIF(DATEDIFF(DD,B.FE_NAC_MENOR,A.FECHA_ATENCION) BETWEEN 110 AND 149,1,0) ID
	FROM #TRAMAHIS A
	INNER JOIN
	#PADRON B ON TRY_CONVERT(INT,A.DOC)=TRY_CONVERT(INT,B.DOC) 
) AS T 
WHERE ID=1

--========================================
---       INDICADOR 
--=========================================

-- SUPLEMENTACION DE HIERRO. 
SELECT *
, IIF(SUPLE=1 AND DEN=1,1,0) NUM
INTO #TEMP2 
FROM (
		SELECT *
		, IIF(
			COD_ITEM in ('Z298','99199.17') AND (
						VALOR_LAB IN ('SF1','SF2','SF3','SF4','SF5')
						OR VALOR_LAB IN ('P01','P02','P03','P04','P05')		
						OR VALOR_LAB IN ('PO1','PO2','PO3','PO4','PO5'))						
		,1,0) SUPLE
		FROM #TEMP1 
) AS T 

--===============================================
-- CRITERIOS DE ELECCION.
SELECT * 
, MAX(NUM) OVER (PARTITION BY DOC) ID_1 --> IDENTIFICAR LOS NI�OS QUE HAN RECIBIDO GOTAS. (1 = NI�O QUE RECIBIO GOTAS | 0 = NI�O QUE NO RECIBIO GOTAS)
INTO #TEMP3 
FROM #TEMP2

--- NI�OS QUE RECIBIERON GOTAS.
SELECT *
INTO #TEMP3_GOTAS 
FROM (
					SELECT * 
					, ROW_NUMBER() OVER (PARTITION BY DOC ORDER BY FECHA_ATENCION ASC, FECHA_REGISTRO ASC) ID_2 --> IDENTIFICO AL PRIMER EESS QUE ENTREGO GOTAS AL NI�O. 
					FROM #TEMP3 
					WHERE ID_1=1 AND NUM=1 --> NI�O QUE RECIBIO GOTAS Y ESTABLECIMIENTO QUE LE DIO LAS GOTAS. 
) AS T 
WHERE ID_2=1 

ALTER TABLE #TEMP3_GOTAS DROP COLUMN ID_2 

--- NI�OS QUE NO RECIBIERON GOTAS.
SELECT * 
INTO  #TEMP3_NOGOTAS 
FROM #TEMP3
WHERE ID_1=0

-- UNION DE LA BASE DE NI�OS FINAL ( CON GOTAS Y SIN GOTAS) 
SELECT *
INTO #TEMP4
FROM #TEMP3_GOTAS
UNION ALL 
SELECT *
FROM #TEMP3_NOGOTAS

--=====================================
-- COLLAPSE
--===================================
SELECT --TIPO_DOC , 
DOC, RENAES, MES ,AÑO
, MAX(DEN) DEN, MAX(NUM) NUM 
INTO #DL1153_2020_04_NOMINAL
FROM #TEMP4
GROUP BY --TIPO_DOC, 
DOC, RENAES, MES , AÑO

SELECT RENAES, MES ,AÑO
, SUM(DEN) DENOMINADOR, SUM(NUM) NUMERADOR
INTO #COLLAPSE2 
FROM #DL1153_2020_04_NOMINAL
GROUP BY RENAES, MES , AÑO

--*********************************************************************************************************************************
-- CALCULO DE NOMINALES
--*********************************************************************************************************************************
SELECT
	N.*
	, MES = case
when N.mes=1 then 'ENERO'
when N.mes=2 then 'FEBRERO'
when N.mes=3 then 'MARZO'
when N.mes=4 then 'ABRIL'
when N.mes=5 then 'MAYO'
when N.mes=6 then 'JUNIO'
when N.mes=7 then 'JULIO' 
when N.mes=8 then 'AGOSTO'
when N.mes=9 then 'SETIEMBRE'
when N.mes=10 then 'OCTUBRE'
when N.mes=11 then 'NOVIEMBRE'
when N.mes=12 then 'DICIEMBRE' end
	, P.[NIÑO PADRON]
FROM
	#DL1153_2020_04_NOMINAL AS N
		LEFT JOIN #PADRON_NOMINAL_30062021 AS P
			ON N.DOC = P.NU_DNI_MENOR
--*********************************************************************************************************************************


SELECT A.RENAES
, B.CAT_ESTAB
, B.AMBITO
, B.UBIGEO
 , CASE WHEN b.DESC_DPTO='LIMA' and B.DESC_PROV not in ('LIMA') then 'LIMA PROVINCIAS'
	WHEN b.DESC_DPTO='LIMA' and B.DESC_PROV in ('LIMA') THEN 'LIMA METROPOLITANA' ELSE B.DESC_DPTO END DEPARTAMENTO
, B.DESC_PROV PROVINCIA
, B.DESC_DIST DISTRITO
, B.DESC_RED 
, B.DESC_MRED
, B.DESC_ESTAB EST_NOMBRE
, C.DIRIS
, A.AÑO
, A.MES
, A.NUMERADOR
, A.DENOMINADOR
INTO #COLLAPSE_FINAL 
FROM #COLLAPSE2 A
INNER JOIN
#RENAES B ON CONVERT(INT,A.RENAES)=CONVERT(INT,B.COD_ESTAB)
LEFT JOIN
Maestro_UBIGEO_20200407 C ON CONVERT(INT,B.UBIGEO)=CONVERT(INT,C.UBIGEO)
WHERE B.CAT_ESTAB IN ('I-1','I-2','I-3','I-4','II-1','II-2','II-E')

--==============================
--BASE FINAL 
--==============================
select RENAES, CAT_ESTAB, AMBITO, RIGHT('000000'+RTRIM(LTRIM(UBIGEO)),6) UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DESC_RED, DESC_MRED, EST_NOMBRE, DIRIS, AÑO
,MES= case
when mes=1 then 'ENERO'
when mes=2 then 'FEBRERO'
when mes=3 then 'MARZO'
when mes=4 then 'ABRIL'
when mes=5 then 'MAYO'
when mes=6 then 'JUNIO'
when mes=7 then 'JULIO' 
when mes=8 then 'AGOSTO'
when mes=9 then 'SETIEMBRE'
when mes=10 then 'OCTUBRE'
when mes=11 then 'NOVIEMBRE'
when mes=12 then 'DICIEMBRE' end
, DENOMINADOR, NUMERADOR
INTO #DL1153_2020_04_CONSOLIDADO
from #COLLAPSE_FINAL

SELECT * FROM #DL1153_2020_04_CONSOLIDADO

