/*==============================================================================
	Indicadores DL1153

Nombre: Porcentaje de ni�as/ni�os reci�n nacidos de parto institucional que reciben vacunas completas antes del alta. 
Sintaxis:

Numerador: Total de ni�as/ni�os del denominador, que recibieron 1 dosis de la vacuna BCG (CPMS: 90585) y 
1 de HVB (CPMS: 90744) antes del alta, seg�n se establece en el esquema nacional de vacunaciones.

Sintaxis: Suma de DNIs que forman parte del denominador que recibieron 1 dosis de la vacuna BCG 
(CPMS: 90585) y 1 de HVB (CPMS: 90744) antes del alta (m�ximo hasta 02 d�as despu�s del nacimiento).

Denominador: Total de ni�as/ni�os nacidos en hospital o instituto* en el periodo de evaluaci�n y 
se encuentran registrados con DNI en el CNV en l�nea, excluyendo los ni�os nacidos con menos de 2000 gr.

Sintaxis: Suma de DNIs �nicos de ni�os nacidos en hospital o instituto* en el periodo de evaluaci�n y
 se encuentran registrados con DNI en el CNV en l�nea, excluyendo los ni�os nacidos con menos de 2000 gr.

Fuente: HIS
�mbito de medici�n: IPRESS.
Periodicidad: Mensual
==============================================================================*/
use BDHIS_MINSA
go

 DROP TABLE #CNV
 DROP TABLE #CNV2
 DROP TABLE #CNV_FINAL
 DROP TABLE #CNV_20210710
 DROP TABLE #TRAMA_HIS
 DROP TABLE #HIS_MINSA
 DROP TABLE #2019
 DROP TABLE #2020
 DROP TABLE #2021
 DROP TABLE #PN_DNI
 DROP TABLE #PADRON
 DROP TABLE #BPN
 DROP TABLE #PADRON_03
 DROP TABLE #PADRONF_03
 DROP TABLE #PADRON_NOMINAL
 DROP TABLE #ATENDIDOS
 DROP TABLE #TMP_1
 DROP TABLE #TMP_01
 DROP TABLE #TMP_02
 DROP TABLE #TMP_2
 DROP TABLE #TMP_3
 DROP TABLE #TMP_4
 DROP TABLE #CRED1_03
 DROP TABLE #CRED2_03
 DROP TABLE #TEMP1
 DROP TABLE #TEMP2
 DROP TABLE #TEMP3
 DROP TABLE #TEMP4
 DROP TABLE #TEMP5
 DROP TABLE #TEMP6
 DROP TABLE #TEMP7
 DROP TABLE #TEMP8
 DROP TABLE #TEMP9
 DROP TABLE #TEMP_10
 DROP TABLE #TEMP_11
 DROP TABLE #TEMP_12
 DROP TABLE #TEMP_19
 DROP TABLE #TEMP_19_1
 DROP TABLE #TEMP_20
 DROP TABLE #TEMP_21
 DROP TABLE #TEMP_22
 DROP TABLE #TEMP_23
 DROP TABLE #TEMP_24
 DROP TABLE #TEMP_25
 DROP TABLE #PRE_COLLAPSE
 DROP TABLE #COLLAPSE_FINAL
 DROP TABLE #COLLAPSE2
 DROP TABLE #COLLAPSE3
 DROP TABLE #COLLAPSE_3
 DROP TABLE #DL1153_2021_06_NOMINAL
 DROP TABLE #DL1153_2021_06_CONSOLIDADO
 DROP TABLE #TRAMAHIS_CG_06_CONSOLIDADO
 DROP TABLE #TRAMAHIS_CG_06_NOMINAL
 DROP TABLE #ELIMINA_MENOR

--=============================================================================
 DROP TABLE #TRAMAHISMINSA_202106_20210720
SELECT
	N.ANIO + RIGHT('00' + N.MES, 2) AS ANIOMES,
	MP.ID_TIPO_DOCUMENTO_PACIENTE 	AS ID_TIPO_DOC,
	MP.ID_GENERO					AS ID_GENERO,
	N.CODIGO_ITEM 					AS COD_ITEM,
	N.VALOR_LAB						AS VALOR_LAB,
	N.TIPO_DIAGNOSTICO				AS ID_TIPITEM,
	ME.CODIGO_UNICO					AS RENAES,
	N.EDAD_REG,
	N.ID_CITA,
	N.FECHA_REGISTRO,

	MP.NUMERO_DOCUMENTO_PACIENTE 	AS NUM_DOC,
	N.FECHA_ATENCION 				AS FECHA_CITA,
	N.FECHA_ATENCION 				AS PERIODO,
	(MP.APELLIDO_PATERNO_PACIENTE + ' ' + MP.APELLIDO_MATERNO_PACIENTE + ' ' + MP.NOMBRES_PACIENTE) AS PACIENTE
INTO
	#TRAMAHISMINSA_202106_20210720
FROM
	NOMINAL_TRAMA_NUEVO AS N
		INNER JOIN MAESTRO_PACIENTE AS MP
			ON N.ID_PACIENTE = MP.ID_PACIENTE
		INNER JOIN MAESTRO_HIS_ESTABLECIMIENTO AS ME
			ON N.ID_ESTABLECIMIENTO = ME.ID_ESTABLECIMIENTO

--=============================================================================
 DROP TABLE #PADRON_NOMINAL_30062021
SELECT
	DNI AS [NU_DNI_MENOR]
	, CNV AS NU_CNV
	, (APELLIDO_PATERNO_MENOR + ' ' + APELLIDO_MATERNO_MENOR + ' ' + NOMBRES_MENOR) AS [NIÑO PADRON]
	, FECHA_DE_NACIMIENTO_MENOR AS [FE_NAC_MENOR]
	, UBIGEO_DISTRITO AS CO_UBIGEO_INEI
	, PROVINCIA
	, DISTRITO
	, TI_DOC_IDENTIDAD = CASE	WHEN CHARINDEX('1', TIPO_DOCUMENTO, 1) != 0 THEN '1'
							WHEN CHARINDEX('3', TIPO_DOCUMENTO, 1) != 0 THEN '3'
					END
	, TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN '1'
					WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN '2'
					WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN '3'
					WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN '4'
					ELSE '9'
					END
	-- , TI_SEGURO_MENOR = CASE WHEN CHARINDEX('1', TIPO_DE_SEGURO, 1) != 0 THEN 'MINSA'
	--				 WHEN CHARINDEX('2', TIPO_DE_SEGURO, 1) != 0 THEN 'ESSALUD'
	--				 WHEN CHARINDEX('3', TIPO_DE_SEGURO, 1) != 0 THEN 'SANIDAD FFAA/PNP'
	--				 WHEN CHARINDEX('4', TIPO_DE_SEGURO, 1) != 0 THEN 'PRIVADO'
	--				 ELSE 'SIN REGISTRO'
	--				 END
INTO
	#PADRON_NOMINAL_30062021
FROM
	PADRON_NOMINAL
--=============================================================================
 DROP TABLE #RENAES
SELECT
	*
INTO
	#RENAES
FROM
	RENAES_20210720
--=============================================================================
 DROP TABLE #CNV_20210710
SELECT
    YEAR(FECHA_PARTO) AS [AÑO CNV]
	, RIGHT(CONCAT('00', MONTH(FECHA_PARTO)), 2) + ' - ' + UPPER(DATENAME(MM, '01/' + CAST(MONTH(FECHA_PARTO) AS NVARCHAR) + '/2021')) AS [MES EVALUACION CNV]
	, CNV AS [NU_CNV]
    , EESS AS [EESS PARTO]
    , CASE WHEN TIPO_DOC = 'DNI/LE' THEN 1 ELSE 0 END AS [TIP_DOC_MADRE]
	, CONT_DOM_MADRE = 92
	, PAIS_DOM_MADRE = 33
	, TIP_LUGAR_NACIDO = 1
	, COD_EESS_PRENATAL AS CO_LOCAL
	, DPTO_DOM_MADRE = '21'
	, PROV_DOM_MADRE = '04'
	, DIST_DOM_MADRE = '01'
    , DNI_G AS [NU_DOC_MADRE]
    , (APELLIDO_PATERNO_GESTANTE + ' ' + APELLIDO_MATERNO_GESTANTE + ' ' + NOMBRES_GESTANTE) AS GESTANTE
    , EESS_PRENATAL AS [EESS PRENATAL]
    , FECHA_PARTO AS [FE_NACIDO]
    , SEMANAS AS [DUR_EMB_PARTO]
	, PESO_NACIDO
INTO
    #CNV_20210710
FROM
    CNV
WHERE
    (
        DNI_G IS NOT NULL
        OR
        DNI_G != ''
    )
--=============================================================================

DECLARE @MES_INICIO INT ,
		@MES_FINAL INT , 
		@YEAR INT

SET @MES_INICIO=1 -- <========= CAMBIAR MES INICIO
SET @MES_FINAL=6 -- <========= CAMBIAR MES FINAL
SET @YEAR=2021 -- <========= CAMBIAR AÑO.

-- **** CAMBIAR BASE DE DATOS ACTUALIZADAS **** 
------------------------------------------------------------------------------------
-- REDUCIENDO BASE DE DATOS.
SELECT *
INTO #CNV
FROM #CNV_20210710
WHERE NU_CNV IS NOT NULL  -- NO SE CONSIDERAN DOCUMENTOS NULOS 
AND NU_CNV NOT IN ('','NULL')  -- NO SE CONSIDERAN DOCUMENTOS VACIOS.  
AND MONTH(CONVERT(DATE,FE_NACIDO))>=@MES_INICIO
AND MONTH(CONVERT(DATE,FE_NACIDO))<=@MES_FINAL
AND YEAR(CONVERT(DATE,FE_NACIDO))=@YEAR
AND TRY_CONVERT(INT,PESO_NACIDO)>=2000 --> SE EXCLUYE NI�OS NACIDOS CON MENOS DE 2000 gr.
AND len(replace(ltrim(rtrim(NU_CNV)),LEFT(ltrim(rtrim(NU_CNV)),1),''))>0
AND TRY_CONVERT(INT,NU_CNV) IS NOT NULL 

-- SELECT *
-- INTO #RENAES
-- FROM BD_HISINDICADORES.DBO.Renaes_20210720

SELECT 
CONVERT(VARCHAR,ID_CITA) ID_CITA
, CONVERT(DATE,PERIODO) FECHA_ATENDIDO
, CASE WHEN id_tipo_doc='1' then '1' -- dni
	WHEN id_tipo_doc='6' then '3' END TIPODOC --cnv  
, NUM_DOC 
, RENAES
, LTRIM(RTRIM(ID_TIPITEM)) TIPO
, LTRIM(RTRIM(COD_ITEM)) COD_ITEM
, LTRIM(RTRIM(VALOR_LAB)) VALOR_LAB 
INTO #HIS_MINSA		
FROM (
		SELECT id_cita, periodo, id_tipo_doc, num_doc, renaes, id_tipitem, cod_item, valor_lab
		FROM #TRAMAHISMINSA_202106_20210720
		WHERE LTRIM(RTRIM(COD_ITEM)) IN ('90585','90744','Z232','Z246') --> CODIGOS ANTERIORES!! 
) AS T 
WHERE YEAR(CONVERT(DATE,PERIODO))>=@YEAR
AND CONVERT(DATE,PERIODO)<=DATEADD(DD,1,DATEADD(MONTH,1,CONVERT(DATE,try_convert(varchar(4),@YEAR)+'-'+try_convert(varchar(2),@MES_FINAL)+'-'+try_convert(varchar(2),'01'))))
AND len(replace(ltrim(rtrim(NUM_DOC)),LEFT(ltrim(rtrim(NUM_DOC)),1),''))>0
AND TRY_CONVERT(INT,NUM_DOC) IS NOT NULL 
AND TRY_CONVERT(INT,id_tipo_doc) IN ('1','6') --> SOLO DNI/CNV

------------------------------------------------------------------------------------

--================
-- CNV
--================
--1. Variables del CNV elegidas para el indicador. 
SELECT 
NU_CNV NUM_DOC
, 1 TIPO_DOC_DNI
, 3 TIPO_DOC_CNV 
, MONTH(CONVERT(DATE,FE_NACIDO)) MES
, AÑO=@YEAR
, CONVERT(DATE,FE_NACIDO) FECHA_NAC
, CO_LOCAL RENAES 
INTO #CNV2 
FROM #CNV_20210710
WHERE CONVERT(INT,TIP_LUGAR_NACIDO)=1 --> PARTOS REALIZADOS EN ESTABLECIMIENTOS DE SALUD. 

--2. Estableciento la ubicacion de residencia segun CNV y Partos en Establecimientos del MINSA Y REGIONALES. (NIVEL: HOSPITAL) 
SELECT *
, DEN=1
INTO #CNV_FINAL
FROM (
		SELECT 
		A.* 
		, B.UBIGEO
		, CASE WHEN B.DESC_DPTO='LIMA' AND B.DESC_PROV NOT IN ('LIMA') THEN 'LIMA PROVINCIAS'
				WHEN B.DESC_DPTO='LIMA' AND B.DESC_PROV IN ('LIMA') THEN 'LIMA METROPOLITANA'
				ELSE B.DESC_DPTO END DESC_DPTO 
		, B.DESC_PROV
		, B.DESC_DIST
		, B.DIRIS
		, B.RED
		, C.AMBITO
		, C.CAT_ESTAB 
		, ISNULL(CONVERT(INT,C.CAMAS),0) CAMAS
		, IIF(ISNULL(CONVERT(INT,C.CAMAS),0)>=50,1,0) DUMMY_CAMAS 
		, C.DESC_ESTAB EESS_NOMBRE
		FROM #CNV2 A 
		INNER JOIN 
		#Renaes C ON CONVERT(INT,A.RENAES)=CONVERT(INT,C.COD_ESTAB)
		INNER JOIN 
		Maestro_UBIGEO_20200407 B ON CONVERT(INT,C.UBIGEO)=CONVERT(INT,B.UBIGEO)
) AS T 
WHERE CONVERT(INT,AMBITO)=1 --> PARTOS EN ESTABLECIMIENTOS DEL MINSA. 
AND
LTRIM(RTRIM(CAT_ESTAB)) in ('II-1','II-2','II-E','III-1','III-E','III-2') 

--==========================
-- ATENDIDOS
--=========================
--UNION DE BASE DE HIS Y CNV
SELECT *		
INTO #ATENDIDOS 
FROM (
		SELECT  A.*
		, CASE WHEN B.FECHA_ATENDIDO IS NOT NULL THEN CONVERT(VARCHAR,A.TIPO_DOC_DNI)+CONVERT(VARCHAR,A.NUM_DOC)
				WHEN C.FECHA_ATENDIDO IS NOT NULL AND B.FECHA_ATENDIDO IS NULL THEN CONVERT(VARCHAR,A.TIPO_DOC_CNV)+CONVERT(VARCHAR,A.NUM_DOC)
				ELSE CONVERT(VARCHAR,A.TIPO_DOC_DNI)+CONVERT(VARCHAR,A.NUM_DOC) END ID_PERSONA 
		, CASE WHEN B.FECHA_ATENDIDO IS NOT NULL THEN B.FECHA_ATENDIDO
				WHEN B.FECHA_ATENDIDO IS NULL AND C.FECHA_ATENDIDO IS NOT NULL THEN C.FECHA_ATENDIDO END FECHA_ATENDIDO
		, CASE WHEN B.ID_CITA IS NOT NULL THEN B.ID_CITA 
				WHEN B.ID_CITA  IS NULL AND C.ID_CITA IS NOT NULL THEN C.ID_CITA END ID_CITA 
		, CASE WHEN B.TIPO IS NOT NULL THEN B.TIPO
				WHEN B.TIPO IS NULL AND C.TIPO IS NOT NULL THEN C.TIPO END TIPO
		, CASE WHEN B.COD_ITEM IS NOT NULL THEN B.COD_ITEM
				WHEN B.COD_ITEM IS NULL AND C.COD_ITEM IS NOT NULL THEN C.COD_ITEM END COD_ITEM
		, CASE WHEN B.VALOR_LAB IS NOT NULL THEN B.VALOR_LAB
				WHEN B.VALOR_LAB IS NULL AND C.VALOR_LAB IS NOT NULL THEN C.VALOR_LAB END VALOR_LAB 
		FROM #CNV_FINAL A 
		LEFT JOIN 
		#HIS_MINSA B ON TRY_CONVERT(INT,A.NUM_DOC)=TRY_CONVERT(INT,B.NUM_DOC) AND TRY_CONVERT(INT,A.TIPO_DOC_DNI)=TRY_CONVERT(INT,B.TIPODOC) 
						AND TRY_CONVERT(INT,A.RENAES)=TRY_CONVERT(INT,B.RENAES) --> EL MISMO ESTABLECIMIENTO DE PARTO DEBEN ENTREGAR LA VACUNA.  [DNI]
		LEFT JOIN 
		#HIS_MINSA C ON TRY_CONVERT(INT,A.NUM_DOC)=TRY_CONVERT(INT,C.NUM_DOC) AND TRY_CONVERT(INT,A.TIPO_DOC_CNV)=TRY_CONVERT(INT,C.TIPODOC) 
						AND TRY_CONVERT(INT,A.RENAES)=TRY_CONVERT(INT,C.RENAES) --> EL MISMO ESTABLECIMIENTO DE PARTO DEBEN ENTREGAR LA VACUNA.  [CNV]
) AS T 

--================================================================
--                      INDICADORES 
--================================================================

--1. NUM_DOC QUE RECIBIERON 1 DOSIS DE VACUNA BCG DENTRO DE LAS 48 HORAS 
SELECT *
, MAX(TEMP_BCG) OVER (PARTITION BY ID_PERSONA) NUM_BCG 
INTO #TEMP1
FROM (
	SELECT *
	, IIF(
	FECHA_ATENDIDO IS NOT NULL
	AND FECHA_NAC IS NOT NULL
	AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENDIDO) BETWEEN 0 AND 2 	
	AND COD_ITEM IN ('90585','Z232'),1,0) TEMP_BCG
	FROM #ATENDIDOS
) AS T 

--2. NUM_DOC QUE RECIBIERON 1 DOSIS DE VACUNA HVB DENTRO DE LAS 48 HORAS 
SELECT *
, MAX(TEMP_HVB) OVER (PARTITION BY ID_PERSONA) NUM_HVB
INTO  #TEMP2
FROM (
	SELECT *
	, IIF(
	FECHA_ATENDIDO IS NOT NULL
	AND FECHA_NAC IS NOT NULL
	AND DATEDIFF(DD,FECHA_NAC,FECHA_ATENDIDO) BETWEEN 0 AND 2 
	AND COD_ITEM IN ('90744','Z246'),1,0) TEMP_HVB
	FROM #TEMP1
) AS T 


--================================================================
--                      INDICADORES 
--================================================================
SELECT
ID_PERSONA
, MES
, AÑO
, UBIGEO
, DESC_DPTO
, DESC_PROV
, DESC_DIST
, DIRIS
, RED
, CAT_ESTAB
, CAMAS
, DUMMY_CAMAS
, EESS_NOMBRE
, RENAES
, MAX(DEN) DEN, MAX(NUM_HVB) NUM_HVB, MAX(NUM_BCG) NUM_BCG 
INTO #TEMP3
FROM #TEMP2
GROUP BY 
ID_PERSONA
, MES
, AÑO
, UBIGEO
, DESC_DPTO
, DESC_PROV
, DESC_DIST
, DIRIS
, RED
, CAT_ESTAB
, CAMAS
, DUMMY_CAMAS
, EESS_NOMBRE
, RENAES

SELECT *
, IIF(NUM_HVB=1 AND NUM_BCG=1,1,0) NUM 
INTO #DL1153_2021_06_NOMINAL
FROM #TEMP3 

SELECT
MES
, AÑO
, UBIGEO
, DESC_DPTO
, DESC_PROV
, DESC_DIST
, DIRIS
, RED
, CAT_ESTAB
, CAMAS
, DUMMY_CAMAS
, EESS_NOMBRE
, RENAES
, SUM(DEN) DENOMINADOR, SUM(NUM) NUMERADOR, SUM(NUM_HVB) NUM_HVB, SUM(NUM_BCG ) NUM_BCG 
INTO #DL1153_2021_06_CONSOLIDADO
FROM #DL1153_2021_06_NOMINAL
GROUP BY 
MES
, AÑO
, UBIGEO
, DESC_DPTO
, DESC_PROV
, DESC_DIST
, DIRIS
, RED
, CAT_ESTAB
, CAMAS
, DUMMY_CAMAS
, EESS_NOMBRE
, RENAES

SELECT * FROM #DL1153_2021_06_CONSOLIDADO

